{
  "patcher": {
    "fileversion": 1,
    "appversion": {
      "major": 8,
      "minor": 6,
      "revision": 2,
      "architecture": "x64",
      "modernui": 1
    },
    "classnamespace": "box",
    "rect": [
      100.0,
      100.0,
      900.0,
      640.0
    ],
    "bglocked": 0,
    "openinpresentation": 1,
    "default_fontsize": 12.0,
    "default_fontface": 0,
    "default_fontname": "Arial",
    "gridonopen": 1,
    "gridsize": [
      15.0,
      15.0
    ],
    "gridsnaponopen": 1,
    "objectsnaponopen": 1,
    "statusbarvisible": 2,
    "toolbarvisible": 1,
    "lefttoolbarpinned": 0,
    "toptoolbarpinned": 0,
    "righttoolbarpinned": 0,
    "bottomtoolbarpinned": 0,
    "toolbars_unpinned_last_save": 0,
    "tallnewobj": 0,
    "boxanimatetime": 200,
    "enablehscroll": 1,
    "enablevscroll": 1,
    "devicewidth": 420.0,
    "description": "AGE·12 real-time sample ager (SP-1200 / MPC60 / MPC3000)",
    "digest": "",
    "tags": "",
    "style": "",
    "subpatcher_template": "",
    "assistshowspatchername": 0,
    "boxes": [
      {
        "box": {
          "id": "obj-6",
          "maxclass": "newobj",
          "text": "plugin~",
          "numinlets": 2,
          "numoutlets": 2,
          "outlettype": [
            "signal",
            "signal"
          ],
          "patching_rect": [
            30,
            340,
            60,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-7",
          "maxclass": "newobj",
          "text": "gen~",
          "numinlets": 2,
          "numoutlets": 2,
          "outlettype": [
            "signal",
            "signal"
          ],
          "patching_rect": [
            30,
            400,
            60,
            22
          ],
          "patcher": {
            "fileversion": 1,
            "appversion": {
              "major": 8,
              "minor": 6,
              "revision": 2,
              "architecture": "x64",
              "modernui": 1
            },
            "classnamespace": "dsp.gen",
            "rect": [
              100.0,
              100.0,
              800.0,
              600.0
            ],
            "bglocked": 0,
            "openinpresentation": 0,
            "default_fontsize": 12.0,
            "default_fontface": 0,
            "default_fontname": "Arial",
            "gridonopen": 1,
            "gridsize": [
              15.0,
              15.0
            ],
            "gridsnaponopen": 1,
            "objectsnaponopen": 1,
            "statusbarvisible": 2,
            "toolbarvisible": 1,
            "lefttoolbarpinned": 0,
            "toptoolbarpinned": 0,
            "righttoolbarpinned": 0,
            "bottomtoolbarpinned": 0,
            "toolbars_unpinned_last_save": 0,
            "tallnewobj": 0,
            "boxanimatetime": 200,
            "enablehscroll": 1,
            "enablevscroll": 1,
            "devicewidth": 0.0,
            "description": "",
            "digest": "",
            "tags": "",
            "style": "",
            "subpatcher_template": "",
            "assistshowspatchername": 0,
            "boxes": [
              {
                "box": {
                  "id": "obj-1",
                  "maxclass": "newobj",
                  "text": "in 1",
                  "numinlets": 0,
                  "numoutlets": 1,
                  "outlettype": [
                    ""
                  ],
                  "patching_rect": [
                    30,
                    30,
                    40,
                    22
                  ]
                }
              },
              {
                "box": {
                  "id": "obj-2",
                  "maxclass": "newobj",
                  "text": "in 2",
                  "numinlets": 0,
                  "numoutlets": 1,
                  "outlettype": [
                    ""
                  ],
                  "patching_rect": [
                    110,
                    30,
                    40,
                    22
                  ]
                }
              },
              {
                "box": {
                  "id": "obj-3",
                  "maxclass": "codebox",
                  "code": "// AGE12 real-time: stereo streaming port of the AGE12 sample-ager chain.\n// Generated by build_device.py - edit there, not here.\n// Latency: 6 samples (dry path is delayed to match).\nParam pitchst(12, min=0, max=24);        // semitones up before the crush\nParam crushrate(26040, min=4000, max=44100);\nParam bitdepth(12, min=4, max=16);\nParam prefilt(0, min=0, max=1);\nParam companded(0, min=0, max=1);        // 0 linear (SP-style), 1 companded (MPC-style)\nParam dacfreq(11000, min=2000, max=20000);\nParam dacres(0.3, min=0, max=1);\nParam satur(0.3, min=0, max=1);\nParam noiselvl(0.12, min=0, max=1);\nParam asymm(0.25, min=0, max=1);\nParam wetmix(1, min=0, max=1);\n\nHistory nL(-1); History kL(0); History kLastL(-1); History ySrcL(0); History outPosL(0); History zL(0);\nHistory s1L(0); History s2L(0); History s3L(0); History s4L(0);\nData xbL(256); Data ybL(1024); Data qbL(256);\nHistory nR(-1); History kR(0); History kLastR(-1); History ySrcR(0); History outPosR(0); History zR(0);\nHistory s1R(0); History s2R(0); History s3R(0); History s4R(0);\nData xbR(256); Data ybR(1024); Data qbR(256);\n\n// ---- parameters, clamped so that unset/zero values can never produce inf or NaN ----\npk = max(0, min(24, pitchst));\ncr = max(4000, min(44100, crushrate));\nbd = max(4, min(16, floor(bitdepth + 0.5)));\npf = max(0, min(1, prefilt));\ncmp = max(0, min(1, companded));\ndf = max(2000, min(20000, dacfreq));\ndres = max(0, min(1, dacres));\nsat = max(0, min(1, satur));\nnz = max(0, min(1, noiselvl));\nasy = max(0, min(1, asymm));\nwm = max(0, min(1, wetmix));\n// ---- values derived from the parameters ----\nr = max(1, pow(2, pk / 12));\nrinv = 1 / r;\nholdstep = samplerate / cr;\nlevels = pow(2, bd - 1) - 1;\nlnK1 = log(56);\nprecut = samplerate * 0.45 * (1 - pf) + cr * 0.45 * pf;\nprex = exp(-6.283185307179586 * precut / samplerate);\nprea = 1 - prex;\nfcn = min(0.99, max(0.001, df / (samplerate * 0.5)));\nf = fcn * 1.16;\nfb = dres * 4 * (1 - 0.15 * f * f);\ndrive = 1 + sat * 3;\ndnorm = tanh(drive);\n\n// ================= channel L =================\na = 0; b = 0; y = 0; h = 0; v = 0; sg = 1; sq = 1; cc = 0; qn = 0; c2 = 0; qv = 0; hs = 0; src = 0;\ni0 = 0; i1 = 0; j0 = 0; j1 = 0; fr = 0; va = 0; vb = 0; w = 0; inp = 0; o = 0;\nnL = nL + 1;\npoke(xbL, in1, mod(nL, 256));\n\n// writer: one pitched-up sample per input sample at most (r >= 1)\ni0 = floor(ySrcL);\ni1 = i0 + 1;\nif (i1 <= nL) {\n    a = peek(xbL, mod(i0, 256));\n    b = peek(xbL, mod(i1, 256));\n    y = a + (b - a) * (ySrcL - i0);\n    if (pf > 0) {\n        zL = prea * y + prex * zL;\n        y = zL;\n    }\n    poke(ybL, y, mod(kL, 1024));\n    h = y;\n    if (holdstep > 1) {\n        hs = floor(kL / holdstep) * holdstep;\n        src = floor(hs + 0.5);\n        if (src > kL) { src = kL; }\n        h = peek(ybL, mod(src, 1024));\n    }\n    v = min(1, max(-1, h));\n    if (cmp > 0.5) {\n        sg = 1;\n        if (v < 0) { sg = -1; }\n        cc = log(1 + 55 * abs(v)) / lnK1;\n        qn = floor(sg * cc * levels + 0.5);\n        c2 = abs(qn) / levels;\n        sq = 1;\n        if (qn < 0) { sq = -1; }\n        qv = sq * ((exp(c2 * lnK1) - 1) / 55);\n    } else {\n        qv = floor(v * levels + 0.5) / levels;\n    }\n    poke(qbL, qv, mod(kL, 256));\n    kLastL = kL;\n    kL = kL + 1;\n    ySrcL = ySrcL + r;\n}\n\n// reader: pitch back down, DAC filter, analog stage\nwetL = 0;\nif (nL >= 6) {\n    j0 = floor(outPosL);\n    fr = outPosL - j0;\n    j1 = j0 + 1;\n    if (j1 > kLastL) {\n        j1 = kLastL;\n        if (j0 > kLastL) { j0 = kLastL; }\n    }\n    va = peek(qbL, mod(j0, 256));\n    vb = peek(qbL, mod(j1, 256));\n    w = va + (vb - va) * fr;\n    outPosL = outPosL + rinv;\n\n    inp = tanh(w - fb * s4L);\n    s1L = s1L + f * (inp - s1L);\n    s2L = s2L + f * (s1L - s2L);\n    s3L = s3L + f * (s2L - s3L);\n    s4L = s4L + f * (s3L - s4L);\n    o = s4L;\n\n    if (o < 0) { o = o * (1 + asy * 0.35); }\n    if (sat > 0) { o = tanh(o * drive) / dnorm; }\n    if (nz > 0) { o = o + noise() * 0.5 * nz * 0.02; }\n    wetL = o;\n}\ndryL = peek(xbL, mod(max(0, nL - 6), 256));\nout1 = dryL * (1 - wm) + wetL * wm;\n\n// ================= channel R =================\na = 0; b = 0; y = 0; h = 0; v = 0; sg = 1; sq = 1; cc = 0; qn = 0; c2 = 0; qv = 0; hs = 0; src = 0;\ni0 = 0; i1 = 0; j0 = 0; j1 = 0; fr = 0; va = 0; vb = 0; w = 0; inp = 0; o = 0;\nnR = nR + 1;\npoke(xbR, in2, mod(nR, 256));\n\n// writer: one pitched-up sample per input sample at most (r >= 1)\ni0 = floor(ySrcR);\ni1 = i0 + 1;\nif (i1 <= nR) {\n    a = peek(xbR, mod(i0, 256));\n    b = peek(xbR, mod(i1, 256));\n    y = a + (b - a) * (ySrcR - i0);\n    if (pf > 0) {\n        zR = prea * y + prex * zR;\n        y = zR;\n    }\n    poke(ybR, y, mod(kR, 1024));\n    h = y;\n    if (holdstep > 1) {\n        hs = floor(kR / holdstep) * holdstep;\n        src = floor(hs + 0.5);\n        if (src > kR) { src = kR; }\n        h = peek(ybR, mod(src, 1024));\n    }\n    v = min(1, max(-1, h));\n    if (cmp > 0.5) {\n        sg = 1;\n        if (v < 0) { sg = -1; }\n        cc = log(1 + 55 * abs(v)) / lnK1;\n        qn = floor(sg * cc * levels + 0.5);\n        c2 = abs(qn) / levels;\n        sq = 1;\n        if (qn < 0) { sq = -1; }\n        qv = sq * ((exp(c2 * lnK1) - 1) / 55);\n    } else {\n        qv = floor(v * levels + 0.5) / levels;\n    }\n    poke(qbR, qv, mod(kR, 256));\n    kLastR = kR;\n    kR = kR + 1;\n    ySrcR = ySrcR + r;\n}\n\n// reader: pitch back down, DAC filter, analog stage\nwetR = 0;\nif (nR >= 6) {\n    j0 = floor(outPosR);\n    fr = outPosR - j0;\n    j1 = j0 + 1;\n    if (j1 > kLastR) {\n        j1 = kLastR;\n        if (j0 > kLastR) { j0 = kLastR; }\n    }\n    va = peek(qbR, mod(j0, 256));\n    vb = peek(qbR, mod(j1, 256));\n    w = va + (vb - va) * fr;\n    outPosR = outPosR + rinv;\n\n    inp = tanh(w - fb * s4R);\n    s1R = s1R + f * (inp - s1R);\n    s2R = s2R + f * (s1R - s2R);\n    s3R = s3R + f * (s2R - s3R);\n    s4R = s4R + f * (s3R - s4R);\n    o = s4R;\n\n    if (o < 0) { o = o * (1 + asy * 0.35); }\n    if (sat > 0) { o = tanh(o * drive) / dnorm; }\n    if (nz > 0) { o = o + noise() * 0.5 * nz * 0.02; }\n    wetR = o;\n}\ndryR = peek(xbR, mod(max(0, nR - 6), 256));\nout2 = dryR * (1 - wm) + wetR * wm;\n",
                  "numinlets": 2,
                  "numoutlets": 2,
                  "outlettype": [
                    "",
                    ""
                  ],
                  "patching_rect": [
                    30,
                    80,
                    700,
                    400
                  ],
                  "fontname": "Menlo",
                  "fontsize": 11.0
                }
              },
              {
                "box": {
                  "id": "obj-4",
                  "maxclass": "newobj",
                  "text": "out 1",
                  "numinlets": 1,
                  "numoutlets": 0,
                  "patching_rect": [
                    30,
                    520,
                    40,
                    22
                  ]
                }
              },
              {
                "box": {
                  "id": "obj-5",
                  "maxclass": "newobj",
                  "text": "out 2",
                  "numinlets": 1,
                  "numoutlets": 0,
                  "patching_rect": [
                    110,
                    520,
                    40,
                    22
                  ]
                }
              }
            ],
            "lines": [
              {
                "patchline": {
                  "destination": [
                    "obj-3",
                    0
                  ],
                  "source": [
                    "obj-1",
                    0
                  ]
                }
              },
              {
                "patchline": {
                  "destination": [
                    "obj-4",
                    0
                  ],
                  "source": [
                    "obj-3",
                    0
                  ]
                }
              },
              {
                "patchline": {
                  "destination": [
                    "obj-3",
                    1
                  ],
                  "source": [
                    "obj-2",
                    0
                  ]
                }
              },
              {
                "patchline": {
                  "destination": [
                    "obj-5",
                    0
                  ],
                  "source": [
                    "obj-3",
                    1
                  ]
                }
              }
            ]
          }
        }
      },
      {
        "box": {
          "id": "obj-8",
          "maxclass": "newobj",
          "text": "plugout~",
          "numinlets": 2,
          "numoutlets": 0,
          "patching_rect": [
            30,
            460,
            70,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-43",
          "maxclass": "comment",
          "text": "AGE-12  SAMPLE AGER",
          "textcolor": [
            0.0941,
            0.1333,
            0.149,
            1.0
          ],
          "fontname": "Menlo",
          "fontsize": 11.0,
          "fontface": 1,
          "textjustification": 0,
          "presentation": 1,
          "presentation_rect": [
            16.0,
            11.0,
            172.0,
            15.0
          ],
          "patching_rect": [
            716.0,
            31.0,
            172.0,
            15.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-44",
          "maxclass": "comment",
          "text": "SP-1200 / MPC60 / MPC3000",
          "textcolor": [
            0.0941,
            0.1333,
            0.149,
            1.0
          ],
          "fontname": "Menlo",
          "fontsize": 8.0,
          "fontface": 0,
          "textjustification": 0,
          "presentation": 1,
          "presentation_rect": [
            16.0,
            26.0,
            172.0,
            12.0
          ],
          "patching_rect": [
            716.0,
            46.0,
            172.0,
            12.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-52",
          "maxclass": "comment",
          "text": "12",
          "textcolor": [
            0.6196,
            0.149,
            0.1176,
            1.0
          ],
          "fontname": "Menlo",
          "fontsize": 15.0,
          "fontface": 1,
          "textjustification": 1,
          "presentation": 1,
          "presentation_rect": [
            372.0,
            10.0,
            40.0,
            16.0
          ],
          "patching_rect": [
            1072.0,
            30.0,
            40.0,
            16.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-53",
          "maxclass": "comment",
          "text": "BIT",
          "textcolor": [
            0.6196,
            0.149,
            0.1176,
            1.0
          ],
          "fontname": "Menlo",
          "fontsize": 8.0,
          "fontface": 1,
          "textjustification": 1,
          "presentation": 1,
          "presentation_rect": [
            372.0,
            27.0,
            40.0,
            10.0
          ],
          "patching_rect": [
            1072.0,
            47.0,
            40.0,
            10.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-54",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            300,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            10.0,
            48.0,
            44.0,
            48.0
          ],
          "varname": "PitchUp",
          "fontname": "Menlo",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.4078,
            0.3686,
            0.2824,
            1.0
          ],
          "activedialcolor": [
            0.7451,
            0.2118,
            0.1647,
            1.0
          ],
          "needlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "activeneedlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "textcolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                12
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Pitch Up",
              "parameter_mmax": 24.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Pitch",
              "parameter_type": 1,
              "parameter_unitstyle": 7
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-55",
          "maxclass": "newobj",
          "text": "prepend pitchst",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            300,
            170,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-56",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            370,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            60.0,
            48.0,
            44.0,
            48.0
          ],
          "varname": "CrushRate",
          "fontname": "Menlo",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.4078,
            0.3686,
            0.2824,
            1.0
          ],
          "activedialcolor": [
            0.7451,
            0.2118,
            0.1647,
            1.0
          ],
          "needlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "activeneedlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "textcolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                26040
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Crush Rate",
              "parameter_mmax": 44100.0,
              "parameter_mmin": 4000.0,
              "parameter_shortname": "Rate",
              "parameter_type": 0,
              "parameter_unitstyle": 3
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-57",
          "maxclass": "newobj",
          "text": "prepend crushrate",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            370,
            170,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-58",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            440,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            110.0,
            48.0,
            44.0,
            48.0
          ],
          "varname": "BitDepth",
          "fontname": "Menlo",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.4078,
            0.3686,
            0.2824,
            1.0
          ],
          "activedialcolor": [
            0.7451,
            0.2118,
            0.1647,
            1.0
          ],
          "needlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "activeneedlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "textcolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                12
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Bit Depth",
              "parameter_mmax": 16.0,
              "parameter_mmin": 4.0,
              "parameter_shortname": "Bits",
              "parameter_type": 1,
              "parameter_unitstyle": 0
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-59",
          "maxclass": "newobj",
          "text": "prepend bitdepth",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            440,
            170,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-60",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            510,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            160.0,
            48.0,
            44.0,
            48.0
          ],
          "varname": "Pre-Filter",
          "fontname": "Menlo",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.4078,
            0.3686,
            0.2824,
            1.0
          ],
          "activedialcolor": [
            0.7451,
            0.2118,
            0.1647,
            1.0
          ],
          "needlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "activeneedlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "textcolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                0
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Pre-Filter",
              "parameter_mmax": 1.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Pre",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-61",
          "maxclass": "newobj",
          "text": "prepend prefilt",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            510,
            170,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-62",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            580,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            210.0,
            48.0,
            44.0,
            48.0
          ],
          "varname": "DACCutoff",
          "fontname": "Menlo",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.4078,
            0.3686,
            0.2824,
            1.0
          ],
          "activedialcolor": [
            0.7451,
            0.2118,
            0.1647,
            1.0
          ],
          "needlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "activeneedlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "textcolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                11000
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "DAC Cutoff",
              "parameter_mmax": 20000.0,
              "parameter_mmin": 2000.0,
              "parameter_shortname": "DAC",
              "parameter_type": 0,
              "parameter_unitstyle": 3
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-63",
          "maxclass": "newobj",
          "text": "prepend dacfreq",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            580,
            170,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-64",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            650,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            260.0,
            48.0,
            44.0,
            48.0
          ],
          "varname": "DACResonance",
          "fontname": "Menlo",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.4078,
            0.3686,
            0.2824,
            1.0
          ],
          "activedialcolor": [
            0.7451,
            0.2118,
            0.1647,
            1.0
          ],
          "needlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "activeneedlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "textcolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                0.3
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "DAC Resonance",
              "parameter_mmax": 1.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Res",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-65",
          "maxclass": "newobj",
          "text": "prepend dacres",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            650,
            170,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-66",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            720,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            310.0,
            48.0,
            44.0,
            48.0
          ],
          "varname": "Drive",
          "fontname": "Menlo",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.4078,
            0.3686,
            0.2824,
            1.0
          ],
          "activedialcolor": [
            0.7451,
            0.2118,
            0.1647,
            1.0
          ],
          "needlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "activeneedlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "textcolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                0.3
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Drive",
              "parameter_mmax": 1.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Drive",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-67",
          "maxclass": "newobj",
          "text": "prepend satur",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            720,
            170,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-68",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            790,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            360.0,
            48.0,
            44.0,
            48.0
          ],
          "varname": "Noise",
          "fontname": "Menlo",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.4078,
            0.3686,
            0.2824,
            1.0
          ],
          "activedialcolor": [
            0.7451,
            0.2118,
            0.1647,
            1.0
          ],
          "needlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "activeneedlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "textcolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                0.12
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Noise",
              "parameter_mmax": 1.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Noise",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-69",
          "maxclass": "newobj",
          "text": "prepend noiselvl",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            790,
            170,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-70",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            860,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            10.0,
            102.0,
            44.0,
            48.0
          ],
          "varname": "Asymmetry",
          "fontname": "Menlo",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.4078,
            0.3686,
            0.2824,
            1.0
          ],
          "activedialcolor": [
            0.7451,
            0.2118,
            0.1647,
            1.0
          ],
          "needlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "activeneedlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "textcolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                0.25
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Asymmetry",
              "parameter_mmax": 1.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Asym",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-71",
          "maxclass": "newobj",
          "text": "prepend asymm",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            860,
            170,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-72",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            930,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            60.0,
            102.0,
            44.0,
            48.0
          ],
          "varname": "Mix",
          "fontname": "Menlo",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.4078,
            0.3686,
            0.2824,
            1.0
          ],
          "activedialcolor": [
            0.7451,
            0.2118,
            0.1647,
            1.0
          ],
          "needlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "activeneedlecolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "textcolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                1.0
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Mix",
              "parameter_mmax": 1.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Mix",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-73",
          "maxclass": "newobj",
          "text": "prepend wetmix",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            930,
            170,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-74",
          "maxclass": "live.toggle",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "parameter_enable": 1,
          "patching_rect": [
            300,
            220,
            24,
            24
          ],
          "presentation": 1,
          "presentation_rect": [
            118.0,
            112.0,
            18.0,
            18.0
          ],
          "varname": "Companded",
          "activecolor": [
            0.7451,
            0.2118,
            0.1647,
            1.0
          ],
          "bgcolor": [
            0.2275,
            0.2118,
            0.1804,
            1.0
          ],
          "bordercolor": [
            0.1176,
            0.1098,
            0.0941,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_enum": [
                "linear",
                "companded"
              ],
              "parameter_initial": [
                0
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Companded",
              "parameter_mmax": 1,
              "parameter_shortname": "Comp",
              "parameter_type": 2
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-75",
          "maxclass": "newobj",
          "text": "prepend companded",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            340,
            220,
            110,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-76",
          "maxclass": "comment",
          "text": "COMPANDED",
          "textcolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "fontname": "Menlo",
          "fontsize": 9.0,
          "fontface": 1,
          "textjustification": 0,
          "presentation": 1,
          "presentation_rect": [
            140.0,
            108.0,
            110.0,
            12.0
          ],
          "patching_rect": [
            840.0,
            128.0,
            110.0,
            12.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-77",
          "maxclass": "comment",
          "text": "MPC-STYLE QUANT",
          "textcolor": [
            0.1569,
            0.1373,
            0.1098,
            1.0
          ],
          "fontname": "Menlo",
          "fontsize": 7.0,
          "fontface": 0,
          "textjustification": 0,
          "presentation": 1,
          "presentation_rect": [
            140.0,
            120.0,
            110.0,
            12.0
          ],
          "patching_rect": [
            840.0,
            140.0,
            110.0,
            12.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-78",
          "maxclass": "comment",
          "text": "---- SIGNAL PATH ----",
          "textcolor": [
            0.3765,
            0.3373,
            0.2431,
            1.0
          ],
          "fontname": "Menlo",
          "fontsize": 7.0,
          "fontface": 0,
          "textjustification": 1,
          "presentation": 1,
          "presentation_rect": [
            260.0,
            98.0,
            150.0,
            12.0
          ],
          "patching_rect": [
            960.0,
            118.0,
            150.0,
            12.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-79",
          "maxclass": "comment",
          "text": "PITCH UP > S&H > 12BIT\nDAC FILTER > PITCH DOWN\nANALOG OUT STAGE",
          "textcolor": [
            0.2745,
            0.2431,
            0.1725,
            1.0
          ],
          "fontname": "Menlo",
          "fontsize": 8.0,
          "fontface": 0,
          "textjustification": 1,
          "presentation": 1,
          "presentation_rect": [
            260.0,
            110.0,
            150.0,
            40.0
          ],
          "patching_rect": [
            960.0,
            130.0,
            150.0,
            40.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-83",
          "maxclass": "comment",
          "text": "SAMPLE AGER // REAL-TIME",
          "textcolor": [
            0.8941,
            0.8588,
            0.7451,
            1.0
          ],
          "fontname": "Menlo",
          "fontsize": 7.0,
          "fontface": 0,
          "textjustification": 0,
          "presentation": 1,
          "presentation_rect": [
            28.0,
            155.0,
            280.0,
            12.0
          ],
          "patching_rect": [
            728.0,
            175.0,
            280.0,
            12.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-84",
          "maxclass": "comment",
          "text": "AGE-12 v1.0",
          "textcolor": [
            0.8941,
            0.8588,
            0.7451,
            1.0
          ],
          "fontname": "Menlo",
          "fontsize": 7.0,
          "fontface": 1,
          "textjustification": 2,
          "presentation": 1,
          "presentation_rect": [
            318.0,
            155.0,
            94.0,
            12.0
          ],
          "patching_rect": [
            1018.0,
            175.0,
            94.0,
            12.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-105",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.5882,
            0.5725,
            0.5098,
            0.1
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1022.0,
            34.0,
            24.0,
            9.0
          ],
          "presentation": 1,
          "presentation_rect": [
            322.0,
            14.0,
            24.0,
            9.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-104",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.5882,
            0.5725,
            0.5098,
            0.1
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            966.0,
            50.0,
            28.0,
            6.0
          ],
          "presentation": 1,
          "presentation_rect": [
            266.0,
            30.0,
            28.0,
            6.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-103",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.5882,
            0.5725,
            0.5098,
            0.1
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            914.0,
            32.0,
            22.0,
            8.0
          ],
          "presentation": 1,
          "presentation_rect": [
            214.0,
            12.0,
            22.0,
            8.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-102",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.0784,
            0.102,
            0.1098,
            0.25
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            804.0,
            33.0,
            2.0,
            26.0
          ],
          "presentation": 1,
          "presentation_rect": [
            104.0,
            13.0,
            2.0,
            26.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-101",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            1.0,
            1.0,
            1.0,
            0.08
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            850.0,
            50.0,
            26.0,
            9.0
          ],
          "presentation": 1,
          "presentation_rect": [
            150.0,
            30.0,
            26.0,
            9.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-100",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            1.0,
            1.0,
            1.0,
            0.07
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            714.0,
            33.0,
            40.0,
            14.0
          ],
          "presentation": 1,
          "presentation_rect": [
            14.0,
            13.0,
            40.0,
            14.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-99",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            1.0,
            0.9686,
            0.8431,
            0.22
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            745.0,
            158.0,
            18.0,
            1.0
          ],
          "presentation": 1,
          "presentation_rect": [
            45.0,
            138.0,
            18.0,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-98",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.1569,
            0.1176,
            0.0471,
            0.26
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1072.0,
            120.0,
            1.0,
            13.0
          ],
          "presentation": 1,
          "presentation_rect": [
            372.0,
            100.0,
            1.0,
            13.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-97",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.1569,
            0.1176,
            0.0471,
            0.28
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1000.0,
            72.0,
            14.0,
            1.0
          ],
          "presentation": 1,
          "presentation_rect": [
            300.0,
            52.0,
            14.0,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-96",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.1569,
            0.1176,
            0.0471,
            0.26
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            830.0,
            123.0,
            1.0,
            10.0
          ],
          "presentation": 1,
          "presentation_rect": [
            130.0,
            103.0,
            1.0,
            10.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-95",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.1569,
            0.1176,
            0.0471,
            0.3
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            757.0,
            69.0,
            11.0,
            1.0
          ],
          "presentation": 1,
          "presentation_rect": [
            57.0,
            49.0,
            11.0,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-94",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            1.0,
            0.9686,
            0.8431,
            0.34
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1091.0,
            80.0,
            16.0,
            1.0
          ],
          "presentation": 1,
          "presentation_rect": [
            391.0,
            60.0,
            16.0,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-93",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            1.0,
            0.9686,
            0.8431,
            0.3
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1041.0,
            144.0,
            12.0,
            1.0
          ],
          "presentation": 1,
          "presentation_rect": [
            341.0,
            124.0,
            12.0,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-92",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            1.0,
            0.9686,
            0.8431,
            0.28
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            962.0,
            116.0,
            1.0,
            12.0
          ],
          "presentation": 1,
          "presentation_rect": [
            262.0,
            96.0,
            1.0,
            12.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-91",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            1.0,
            0.9686,
            0.8431,
            0.32
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            901.0,
            142.0,
            19.0,
            1.0
          ],
          "presentation": 1,
          "presentation_rect": [
            201.0,
            122.0,
            19.0,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-90",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            1.0,
            0.9686,
            0.8431,
            0.3
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            788.0,
            79.0,
            1.0,
            9.0
          ],
          "presentation": 1,
          "presentation_rect": [
            88.0,
            59.0,
            1.0,
            9.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-89",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            1.0,
            0.9686,
            0.8431,
            0.38
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            723.0,
            140.0,
            14.0,
            1.0
          ],
          "presentation": 1,
          "presentation_rect": [
            23.0,
            120.0,
            14.0,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-88",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.4078,
            0.3922,
            0.3529,
            1.0
          ],
          "border": 1,
          "rounded": 2.5,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1111.0,
            180.0,
            5.0,
            5.0
          ],
          "presentation": 1,
          "presentation_rect": [
            411.0,
            160.0,
            5.0,
            5.0
          ],
          "bordercolor": [
            0.149,
            0.1412,
            0.1255,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-87",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.4078,
            0.3922,
            0.3529,
            1.0
          ],
          "border": 1,
          "rounded": 2.5,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            704.0,
            180.0,
            5.0,
            5.0
          ],
          "presentation": 1,
          "presentation_rect": [
            4.0,
            160.0,
            5.0,
            5.0
          ],
          "bordercolor": [
            0.149,
            0.1412,
            0.1255,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-86",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.4078,
            0.3922,
            0.3529,
            1.0
          ],
          "border": 1,
          "rounded": 2.5,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1111.0,
            24.0,
            5.0,
            5.0
          ],
          "presentation": 1,
          "presentation_rect": [
            411.0,
            4.0,
            5.0,
            5.0
          ],
          "bordercolor": [
            0.149,
            0.1412,
            0.1255,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-85",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.4078,
            0.3922,
            0.3529,
            1.0
          ],
          "border": 1,
          "rounded": 2.5,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            704.0,
            24.0,
            5.0,
            5.0
          ],
          "presentation": 1,
          "presentation_rect": [
            4.0,
            4.0,
            5.0,
            5.0
          ],
          "bordercolor": [
            0.149,
            0.1412,
            0.1255,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-82",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.7451,
            0.2118,
            0.1647,
            1.0
          ],
          "border": 1,
          "rounded": 3.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            716.0,
            178.0,
            6.0,
            6.0
          ],
          "presentation": 1,
          "presentation_rect": [
            16.0,
            158.0,
            6.0,
            6.0
          ],
          "bordercolor": [
            0.3765,
            0.0863,
            0.0627,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-81",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.502,
            0.4941,
            0.4627,
            1.0
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            700.0,
            173.0,
            420.0,
            1.0
          ],
          "presentation": 1,
          "presentation_rect": [
            0.0,
            153.0,
            420.0,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-80",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.1686,
            0.1647,
            0.1608,
            1.0
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            700.0,
            173.0,
            420.0,
            16.0
          ],
          "presentation": 1,
          "presentation_rect": [
            0.0,
            153.0,
            420.0,
            16.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-51",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.8706,
            0.8353,
            0.6902,
            1.0
          ],
          "border": 1,
          "rounded": 1.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1072.0,
            28.0,
            40.0,
            34.0
          ],
          "presentation": 1,
          "presentation_rect": [
            372.0,
            8.0,
            40.0,
            34.0
          ],
          "bordercolor": [
            0.5882,
            0.502,
            0.2745,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-50",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.0941,
            0.0941,
            0.098,
            1.0
          ],
          "border": 1,
          "rounded": 3.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1011.0,
            27.0,
            52.0,
            36.0
          ],
          "presentation": 1,
          "presentation_rect": [
            311.0,
            7.0,
            52.0,
            36.0
          ],
          "bordercolor": [
            0.3608,
            0.3529,
            0.3294,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-49",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.302,
            0.2824,
            0.2353,
            0.55
          ],
          "border": 0,
          "rounded": 3.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1010.0,
            26.0,
            54.0,
            38.0
          ],
          "presentation": 1,
          "presentation_rect": [
            310.0,
            6.0,
            54.0,
            38.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-48",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.0941,
            0.0941,
            0.098,
            1.0
          ],
          "border": 1,
          "rounded": 3.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            957.0,
            27.0,
            52.0,
            36.0
          ],
          "presentation": 1,
          "presentation_rect": [
            257.0,
            7.0,
            52.0,
            36.0
          ],
          "bordercolor": [
            0.3608,
            0.3529,
            0.3294,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-47",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.302,
            0.2824,
            0.2353,
            0.55
          ],
          "border": 0,
          "rounded": 3.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            956.0,
            26.0,
            54.0,
            38.0
          ],
          "presentation": 1,
          "presentation_rect": [
            256.0,
            6.0,
            54.0,
            38.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-46",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.0941,
            0.0941,
            0.098,
            1.0
          ],
          "border": 1,
          "rounded": 3.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            903.0,
            27.0,
            52.0,
            36.0
          ],
          "presentation": 1,
          "presentation_rect": [
            203.0,
            7.0,
            52.0,
            36.0
          ],
          "bordercolor": [
            0.3608,
            0.3529,
            0.3294,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-45",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.302,
            0.2824,
            0.2353,
            0.55
          ],
          "border": 0,
          "rounded": 3.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            902.0,
            26.0,
            54.0,
            38.0
          ],
          "presentation": 1,
          "presentation_rect": [
            202.0,
            6.0,
            54.0,
            38.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-42",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            1.0,
            1.0,
            1.0,
            0.1
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            712.0,
            30.0,
            178.0,
            6.0
          ],
          "presentation": 1,
          "presentation_rect": [
            12.0,
            10.0,
            178.0,
            6.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-41",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.5451,
            0.6275,
            0.6667,
            1.0
          ],
          "border": 0,
          "rounded": 1.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            712.0,
            30.0,
            178.0,
            30.0
          ],
          "presentation": 1,
          "presentation_rect": [
            12.0,
            10.0,
            178.0,
            30.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-40",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.1176,
            0.1412,
            0.149,
            1.0
          ],
          "border": 0,
          "rounded": 2.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            710.0,
            28.0,
            182.0,
            34.0
          ],
          "presentation": 1,
          "presentation_rect": [
            10.0,
            8.0,
            182.0,
            34.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-39",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            1.0,
            0.9804,
            0.8824,
            0.35
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            702.0,
            22.0,
            416.0,
            1.0
          ],
          "presentation": 1,
          "presentation_rect": [
            2.0,
            2.0,
            416.0,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-38",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.5098,
            0.3608,
            0.102,
            0.17
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1117.0,
            20.0,
            3.0,
            153.0
          ],
          "presentation": 1,
          "presentation_rect": [
            417.0,
            0.0,
            3.0,
            153.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-37",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.5098,
            0.3608,
            0.102,
            0.17
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            700.0,
            20.0,
            3.0,
            153.0
          ],
          "presentation": 1,
          "presentation_rect": [
            0.0,
            0.0,
            3.0,
            153.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-36",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.5098,
            0.3608,
            0.102,
            0.17
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            700.0,
            20.0,
            420.0,
            3.0
          ],
          "presentation": 1,
          "presentation_rect": [
            0.0,
            0.0,
            420.0,
            3.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-35",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.5098,
            0.3608,
            0.102,
            0.17
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1113.0,
            20.0,
            7.0,
            153.0
          ],
          "presentation": 1,
          "presentation_rect": [
            413.0,
            0.0,
            7.0,
            153.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-34",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.5098,
            0.3608,
            0.102,
            0.17
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            700.0,
            20.0,
            7.0,
            153.0
          ],
          "presentation": 1,
          "presentation_rect": [
            0.0,
            0.0,
            7.0,
            153.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-33",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.5098,
            0.3608,
            0.102,
            0.17
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            700.0,
            20.0,
            420.0,
            7.0
          ],
          "presentation": 1,
          "presentation_rect": [
            0.0,
            0.0,
            420.0,
            7.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-32",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.251,
            0.1804,
            0.0784,
            0.2
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            958.0,
            64.0,
            30.0,
            7.0
          ],
          "presentation": 1,
          "presentation_rect": [
            258.0,
            44.0,
            30.0,
            7.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-31",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.251,
            0.1804,
            0.0784,
            0.2
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1056.0,
            146.0,
            50.0,
            14.0
          ],
          "presentation": 1,
          "presentation_rect": [
            356.0,
            126.0,
            50.0,
            14.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-30",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.251,
            0.1804,
            0.0784,
            0.2
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            714.0,
            152.0,
            30.0,
            12.0
          ],
          "presentation": 1,
          "presentation_rect": [
            14.0,
            132.0,
            30.0,
            12.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-29",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.251,
            0.1804,
            0.0784,
            0.2
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            896.0,
            120.0,
            34.0,
            16.0
          ],
          "presentation": 1,
          "presentation_rect": [
            196.0,
            100.0,
            34.0,
            16.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-28",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.251,
            0.1804,
            0.0784,
            0.2
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            780.0,
            140.0,
            44.0,
            10.0
          ],
          "presentation": 1,
          "presentation_rect": [
            80.0,
            120.0,
            44.0,
            10.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-27",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.251,
            0.1804,
            0.0784,
            0.2
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1038.0,
            64.0,
            66.0,
            8.0
          ],
          "presentation": 1,
          "presentation_rect": [
            338.0,
            44.0,
            66.0,
            8.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-26",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.251,
            0.1804,
            0.0784,
            0.2
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            950.0,
            118.0,
            40.0,
            11.0
          ],
          "presentation": 1,
          "presentation_rect": [
            250.0,
            98.0,
            40.0,
            11.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-25",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.251,
            0.1804,
            0.0784,
            0.2
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            850.0,
            64.0,
            76.0,
            9.0
          ],
          "presentation": 1,
          "presentation_rect": [
            150.0,
            44.0,
            76.0,
            9.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-24",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.251,
            0.1804,
            0.0784,
            0.2
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            706.0,
            116.0,
            62.0,
            13.0
          ],
          "presentation": 1,
          "presentation_rect": [
            6.0,
            96.0,
            62.0,
            13.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-23",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.2745,
            0.1961,
            0.0706,
            0.19
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            703.0,
            165.0,
            414.0,
            7.0
          ],
          "presentation": 1,
          "presentation_rect": [
            3.0,
            145.0,
            414.0,
            7.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-22",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.2745,
            0.1961,
            0.0706,
            0.14
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            703.0,
            158.0,
            414.0,
            7.0
          ],
          "presentation": 1,
          "presentation_rect": [
            3.0,
            138.0,
            414.0,
            7.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-21",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.2745,
            0.1961,
            0.0706,
            0.1
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            703.0,
            150.0,
            414.0,
            7.0
          ],
          "presentation": 1,
          "presentation_rect": [
            3.0,
            130.0,
            414.0,
            7.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-20",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.2745,
            0.1961,
            0.0706,
            0.07
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            703.0,
            141.0,
            414.0,
            7.0
          ],
          "presentation": 1,
          "presentation_rect": [
            3.0,
            121.0,
            414.0,
            7.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-19",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.2745,
            0.1961,
            0.0706,
            0.05
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            703.0,
            132.0,
            414.0,
            7.0
          ],
          "presentation": 1,
          "presentation_rect": [
            3.0,
            112.0,
            414.0,
            7.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-18",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.4392,
            0.3216,
            0.1098,
            0.18
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1040.0,
            22.0,
            3.0,
            150.0
          ],
          "presentation": 1,
          "presentation_rect": [
            340.0,
            2.0,
            3.0,
            150.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-17",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.4392,
            0.3216,
            0.1098,
            0.13
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            905.0,
            22.0,
            6.0,
            150.0
          ],
          "presentation": 1,
          "presentation_rect": [
            205.0,
            2.0,
            6.0,
            150.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-16",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.4392,
            0.3216,
            0.1098,
            0.22
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            758.0,
            22.0,
            2.0,
            150.0
          ],
          "presentation": 1,
          "presentation_rect": [
            58.0,
            2.0,
            2.0,
            150.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-15",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.4392,
            0.3216,
            0.1098,
            0.18
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            866.0,
            22.0,
            3.0,
            150.0
          ],
          "presentation": 1,
          "presentation_rect": [
            166.0,
            2.0,
            3.0,
            150.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-14",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.4392,
            0.3216,
            0.1098,
            0.15
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1077.0,
            22.0,
            11.0,
            150.0
          ],
          "presentation": 1,
          "presentation_rect": [
            377.0,
            2.0,
            11.0,
            150.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-13",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.4392,
            0.3216,
            0.1098,
            0.22
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1001.0,
            22.0,
            4.0,
            150.0
          ],
          "presentation": 1,
          "presentation_rect": [
            301.0,
            2.0,
            4.0,
            150.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-12",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.4392,
            0.3216,
            0.1098,
            0.14
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            936.0,
            22.0,
            14.0,
            150.0
          ],
          "presentation": 1,
          "presentation_rect": [
            236.0,
            2.0,
            14.0,
            150.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-11",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.4392,
            0.3216,
            0.1098,
            0.2
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            812.0,
            22.0,
            5.0,
            150.0
          ],
          "presentation": 1,
          "presentation_rect": [
            112.0,
            2.0,
            5.0,
            150.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-10",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.4392,
            0.3216,
            0.1098,
            0.17
          ],
          "border": 0,
          "rounded": 0.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            737.0,
            22.0,
            9.0,
            150.0
          ],
          "presentation": 1,
          "presentation_rect": [
            37.0,
            2.0,
            9.0,
            150.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-9",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.7294,
            0.6902,
            0.5765,
            1.0
          ],
          "border": 2,
          "rounded": 5.0,
          "mode": 1,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            700.0,
            20.0,
            420.0,
            169.0
          ],
          "presentation": 1,
          "presentation_rect": [
            0.0,
            0.0,
            420.0,
            169.0
          ],
          "bordercolor": [
            0.3294,
            0.302,
            0.2353,
            1.0
          ],
          "grad1": [
            0.7882,
            0.749,
            0.6275,
            1.0
          ],
          "grad2": [
            0.6588,
            0.6157,
            0.4941,
            1.0
          ],
          "proportion": 0.5,
          "bgfillcolor": {
            "angle": 270.0,
            "autogradient": 0,
            "color": [
              0.7294,
              0.6902,
              0.5765,
              1.0
            ],
            "color1": [
              0.7882,
              0.749,
              0.6275,
              1.0
            ],
            "color2": [
              0.6588,
              0.6157,
              0.4941,
              1.0
            ],
            "proportion": 0.5,
            "type": "gradient"
          }
        }
      },
      {
        "box": {
          "id": "obj-106",
          "maxclass": "newobj",
          "text": "unpack 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.",
          "numinlets": 1,
          "numoutlets": 11,
          "outlettype": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "patching_rect": [
            30,
            250,
            400,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-107",
          "maxclass": "message",
          "text": "12 26040 12 0 11000 0.3 0.3 0.12 0.25 1 0",
          "numinlets": 2,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            30,
            130,
            380,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-108",
          "maxclass": "textbutton",
          "text": "SP-1200",
          "numinlets": 1,
          "numoutlets": 3,
          "outlettype": [
            "",
            "",
            "int"
          ],
          "patching_rect": [
            450,
            130,
            70,
            22
          ],
          "presentation": 1,
          "presentation_rect": [
            205.0,
            8.0,
            50.0,
            34.0
          ],
          "mode": 0,
          "fontname": "Menlo",
          "fontsize": 8.0,
          "fontface": 1,
          "bgcolor": [
            0.0941,
            0.0941,
            0.098,
            1.0
          ],
          "bgoncolor": [
            0.3765,
            0.3608,
            0.3137,
            1.0
          ],
          "bordercolor": [
            0.3608,
            0.3529,
            0.3294,
            1.0
          ],
          "textcolor": [
            0.8941,
            0.8588,
            0.7451,
            1.0
          ],
          "textoncolor": [
            1.0,
            1.0,
            1.0,
            1.0
          ],
          "usebgoncolor": 1,
          "rounded": 3.0
        }
      },
      {
        "box": {
          "id": "obj-109",
          "maxclass": "message",
          "text": "12 40000 12 0 16000 0.12 0.18 0.06 0.1 1 1",
          "numinlets": 2,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            30,
            160,
            380,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-110",
          "maxclass": "textbutton",
          "text": "MPC60",
          "numinlets": 1,
          "numoutlets": 3,
          "outlettype": [
            "",
            "",
            "int"
          ],
          "patching_rect": [
            450,
            160,
            70,
            22
          ],
          "presentation": 1,
          "presentation_rect": [
            259.0,
            8.0,
            50.0,
            34.0
          ],
          "mode": 0,
          "fontname": "Menlo",
          "fontsize": 8.0,
          "fontface": 1,
          "bgcolor": [
            0.0941,
            0.0941,
            0.098,
            1.0
          ],
          "bgoncolor": [
            0.3765,
            0.3608,
            0.3137,
            1.0
          ],
          "bordercolor": [
            0.3608,
            0.3529,
            0.3294,
            1.0
          ],
          "textcolor": [
            0.8941,
            0.8588,
            0.7451,
            1.0
          ],
          "textoncolor": [
            1.0,
            1.0,
            1.0,
            1.0
          ],
          "usebgoncolor": 1,
          "rounded": 3.0
        }
      },
      {
        "box": {
          "id": "obj-111",
          "maxclass": "message",
          "text": "12 44100 16 0 19000 0.0 0.08 0.02 0.0 1 0",
          "numinlets": 2,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            30,
            190,
            380,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-112",
          "maxclass": "textbutton",
          "text": "MPC3000",
          "numinlets": 1,
          "numoutlets": 3,
          "outlettype": [
            "",
            "",
            "int"
          ],
          "patching_rect": [
            450,
            190,
            70,
            22
          ],
          "presentation": 1,
          "presentation_rect": [
            313.0,
            8.0,
            50.0,
            34.0
          ],
          "mode": 0,
          "fontname": "Menlo",
          "fontsize": 8.0,
          "fontface": 1,
          "bgcolor": [
            0.0941,
            0.0941,
            0.098,
            1.0
          ],
          "bgoncolor": [
            0.3765,
            0.3608,
            0.3137,
            1.0
          ],
          "bordercolor": [
            0.3608,
            0.3529,
            0.3294,
            1.0
          ],
          "textcolor": [
            0.8941,
            0.8588,
            0.7451,
            1.0
          ],
          "textoncolor": [
            1.0,
            1.0,
            1.0,
            1.0
          ],
          "usebgoncolor": 1,
          "rounded": 3.0
        }
      }
    ],
    "lines": [
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-6",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-8",
            0
          ],
          "source": [
            "obj-7",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            1
          ],
          "source": [
            "obj-6",
            1
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-8",
            1
          ],
          "source": [
            "obj-7",
            1
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-55",
            0
          ],
          "source": [
            "obj-54",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-55",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-57",
            0
          ],
          "source": [
            "obj-56",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-57",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-59",
            0
          ],
          "source": [
            "obj-58",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-59",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-61",
            0
          ],
          "source": [
            "obj-60",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-61",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-63",
            0
          ],
          "source": [
            "obj-62",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-63",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-65",
            0
          ],
          "source": [
            "obj-64",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-65",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-67",
            0
          ],
          "source": [
            "obj-66",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-67",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-69",
            0
          ],
          "source": [
            "obj-68",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-69",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-71",
            0
          ],
          "source": [
            "obj-70",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-71",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-73",
            0
          ],
          "source": [
            "obj-72",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-73",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-75",
            0
          ],
          "source": [
            "obj-74",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-75",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-54",
            0
          ],
          "source": [
            "obj-106",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-56",
            0
          ],
          "source": [
            "obj-106",
            1
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-58",
            0
          ],
          "source": [
            "obj-106",
            2
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-60",
            0
          ],
          "source": [
            "obj-106",
            3
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-62",
            0
          ],
          "source": [
            "obj-106",
            4
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-64",
            0
          ],
          "source": [
            "obj-106",
            5
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-66",
            0
          ],
          "source": [
            "obj-106",
            6
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-68",
            0
          ],
          "source": [
            "obj-106",
            7
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-70",
            0
          ],
          "source": [
            "obj-106",
            8
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-72",
            0
          ],
          "source": [
            "obj-106",
            9
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-74",
            0
          ],
          "source": [
            "obj-106",
            10
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-107",
            0
          ],
          "source": [
            "obj-108",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-106",
            0
          ],
          "source": [
            "obj-107",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-109",
            0
          ],
          "source": [
            "obj-110",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-106",
            0
          ],
          "source": [
            "obj-109",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-111",
            0
          ],
          "source": [
            "obj-112",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-106",
            0
          ],
          "source": [
            "obj-111",
            0
          ]
        }
      }
    ]
  }
}
