#!/usr/bin/env python3
"""Generates the AGE·12 Max for Live device.

  python3 build_device.py   ->   AGE12.genexpr   (the DSP, paste-able into any gen~ codebox)
                                 AGE12.maxpat    (patcher JSON: gen~ + live.* UI)
                                 AGE12.amxd      (Max for Live audio effect)

The DSP is the streaming port of the AGE·12 chain from ../age12-rt/age12_core.h
(pitch up -> pre-LP -> S&H -> quantise -> pitch down -> DAC filter -> analog stage), stereo, with
the dry signal delayed by the same latency so Mix stays phase-aligned.
"""
import json, struct

LAT = 6      # latency in samples: ceil(rMax)+2 with rMax = 2^(24/12) = 4
XN, YN, QN = 256, 1024, 256

PARAMS = [  # message name, longname, short, min, max, default, unitstyle, type(0 float, 1 int)
    ("pitchst",   "Pitch Up", "Pitch", 0,     24,    12,    7, 1),
    ("crushrate", "Crush Rate", "Rate", 4000, 44100, 26040, 3, 0),
    ("bitdepth",  "Bit Depth", "Bits",  4,    16,    12,    0, 1),
    ("prefilt",   "Pre-Filter", "Pre",  0,    1,     0,     1, 0),
    ("dacfreq",   "DAC Cutoff", "DAC",  2000, 20000, 11000, 3, 0),
    ("dacres",    "DAC Resonance", "Res", 0,  1,     0.30,  1, 0),
    ("satur",     "Drive", "Drive",     0,    1,     0.30,  1, 0),
    ("noiselvl",  "Noise", "Noise",     0,    1,     0.12,  1, 0),
    ("asymm",     "Asymmetry", "Asym",  0,    1,     0.25,  1, 0),
    ("wetmix",    "Mix", "Mix",         0,    1,     1.0,   1, 0),
]
PRESETS = {  # pitch is left alone (as in the web app); order = unpack outlets below
    "SP-1200": dict(crushrate=26040, bitdepth=12, prefilt=0, dacfreq=11000, dacres=0.30, satur=0.30, noiselvl=0.12, asymm=0.25, comp=0),
    "MPC60":   dict(crushrate=40000, bitdepth=12, prefilt=0, dacfreq=16000, dacres=0.12, satur=0.18, noiselvl=0.06, asymm=0.10, comp=1),
    "MPC3000": dict(crushrate=44100, bitdepth=16, prefilt=0, dacfreq=19000, dacres=0.00, satur=0.08, noiselvl=0.02, asymm=0.00, comp=0),
}

def channel(c, inp, out):
    return f"""
// ================= channel {c} =================
a = 0; b = 0; y = 0; h = 0; v = 0; sg = 1; sq = 1; cc = 0; qn = 0; c2 = 0; qv = 0; hs = 0; src = 0;
i0 = 0; i1 = 0; j0 = 0; j1 = 0; fr = 0; va = 0; vb = 0; w = 0; inp = 0; o = 0;
n{c} = n{c} + 1;
poke(xb{c}, {inp}, mod(n{c}, {XN}));

// writer: one pitched-up sample per input sample at most (r >= 1)
i0 = floor(ySrc{c});
i1 = i0 + 1;
if (i1 <= n{c}) {{
    a = peek(xb{c}, mod(i0, {XN}));
    b = peek(xb{c}, mod(i1, {XN}));
    y = a + (b - a) * (ySrc{c} - i0);
    if (prefilt > 0) {{
        z{c} = prea * y + prex * z{c};
        y = z{c};
    }}
    poke(yb{c}, y, mod(k{c}, {YN}));
    h = y;
    if (holdstep > 1) {{
        hs = floor(k{c} / holdstep) * holdstep;
        src = floor(hs + 0.5);
        if (src > k{c}) {{ src = k{c}; }}
        h = peek(yb{c}, mod(src, {YN}));
    }}
    v = min(1, max(-1, h));
    if (companded > 0.5) {{
        sg = 1;
        if (v < 0) {{ sg = -1; }}
        cc = log(1 + 55 * abs(v)) / lnK1;
        qn = floor(sg * cc * levels + 0.5);
        c2 = abs(qn) / levels;
        sq = 1;
        if (qn < 0) {{ sq = -1; }}
        qv = sq * ((exp(c2 * lnK1) - 1) / 55);
    }} else {{
        qv = floor(v * levels + 0.5) / levels;
    }}
    poke(qb{c}, qv, mod(k{c}, {QN}));
    kLast{c} = k{c};
    k{c} = k{c} + 1;
    ySrc{c} = ySrc{c} + r;
}}

// reader: pitch back down, DAC filter, analog stage
wet{c} = 0;
if (n{c} >= {LAT}) {{
    j0 = floor(outPos{c});
    fr = outPos{c} - j0;
    j1 = j0 + 1;
    if (j1 > kLast{c}) {{
        j1 = kLast{c};
        if (j0 > kLast{c}) {{ j0 = kLast{c}; }}
    }}
    va = peek(qb{c}, mod(j0, {QN}));
    vb = peek(qb{c}, mod(j1, {QN}));
    w = va + (vb - va) * fr;
    outPos{c} = outPos{c} + rinv;

    inp = tanh(w - fb * s4{c});
    s1{c} = s1{c} + f * (inp - s1{c});
    s2{c} = s2{c} + f * (s1{c} - s2{c});
    s3{c} = s3{c} + f * (s2{c} - s3{c});
    s4{c} = s4{c} + f * (s3{c} - s4{c});
    o = s4{c};

    if (o < 0) {{ o = o * (1 + asymm * 0.35); }}
    if (satur > 0) {{ o = tanh(o * drive) / dnorm; }}
    if (noiselvl > 0) {{ o = o + noise() * 0.5 * noiselvl * 0.02; }}
    wet{c} = o;
}}
dry{c} = peek(xb{c}, mod(max(0, n{c} - {LAT}), {XN}));
{out} = dry{c} * (1 - wetmix) + wet{c} * wetmix;
"""

def genexpr():
    head = f"""// AGE12 real-time: stereo streaming port of the AGE12 sample-ager chain.
// Generated by build_device.py - edit there, not here.
// Latency: {LAT} samples (dry path is delayed to match).
Param pitchst(12, min=0, max=24);        // semitones up before the crush
Param crushrate(26040, min=4000, max=44100);
Param bitdepth(12, min=4, max=16);
Param prefilt(0, min=0, max=1);
Param companded(0, min=0, max=1);        // 0 linear (SP-style), 1 companded (MPC-style)
Param dacfreq(11000, min=2000, max=20000);
Param dacres(0.3, min=0, max=1);
Param satur(0.3, min=0, max=1);
Param noiselvl(0.12, min=0, max=1);
Param asymm(0.25, min=0, max=1);
Param wetmix(1, min=0, max=1);

"""
    state = ""
    for c in "LR":
        state += f"""History n{c}(-1); History k{c}(0); History kLast{c}(-1); History ySrc{c}(0); History outPos{c}(0); History z{c}(0);
History s1{c}(0); History s2{c}(0); History s3{c}(0); History s4{c}(0);
Data xb{c}({XN}); Data yb{c}({YN}); Data qb{c}({QN});
"""
    derived = """
// ---- values derived from the parameters ----
r = max(1, pow(2, max(0, pitchst) / 12));
rinv = 1 / r;
holdstep = samplerate / crushrate;
levels = pow(2, floor(bitdepth + 0.5) - 1) - 1;
lnK1 = log(56);
precut = samplerate * 0.45 * (1 - prefilt) + crushrate * 0.45 * prefilt;
prex = exp(-6.283185307179586 * precut / samplerate);
prea = 1 - prex;
fcn = min(0.99, max(0.001, dacfreq / (samplerate * 0.5)));
f = fcn * 1.16;
fb = dacres * 4 * (1 - 0.15 * f * f);
drive = 1 + satur * 3;
dnorm = tanh(drive);
"""
    return head + state + derived + channel("L", "in1", "out1") + channel("R", "in2", "out2")

# ---------------------------------------------------------------- patcher
_id = [0]
def nid():
    _id[0] += 1
    return f"obj-{_id[0]}"

def box(**kw):
    return {"box": kw}

def finish(boxes, lines, width, description):
    patcher = {
        "fileversion": 1,
        "appversion": {"major": 8, "minor": 6, "revision": 2, "architecture": "x64", "modernui": 1},
        "classnamespace": "box",
        "rect": [100.0, 100.0, 900.0, 640.0],
        "bglocked": 0, "openinpresentation": 1, "default_fontsize": 12.0, "default_fontface": 0,
        "default_fontname": "Arial", "gridonopen": 1, "gridsize": [15.0, 15.0], "gridsnaponopen": 1,
        "objectsnaponopen": 1, "statusbarvisible": 2, "toolbarvisible": 1, "lefttoolbarpinned": 0,
        "toptoolbarpinned": 0, "righttoolbarpinned": 0, "bottomtoolbarpinned": 0, "toolbars_unpinned_last_save": 0,
        "tallnewobj": 0, "boxanimatetime": 200, "enablehscroll": 1, "enablevscroll": 1, "devicewidth": width,
        "description": description, "digest": "", "tags": "",
        "style": "", "subpatcher_template": "", "assistshowspatchername": 0,
        "boxes": boxes, "lines": lines,
    }
    return {"patcher": patcher}

def build_patcher(code, ui=True, thru=False):
    boxes, lines = [], []
    def add(b):
        boxes.append(b); return b["box"]["id"]
    def line(src, so, dst, di):
        lines.append({"patchline": {"destination": [dst, di], "source": [src, so]}})

    # ---- gen~ with embedded patcher
    gin = [box(id=nid(), maxclass="newobj", text=f"in {i}", numinlets=0, numoutlets=1, outlettype=[""], patching_rect=[30 + 80 * (i - 1), 30, 40, 22]) for i in (1, 2)]
    gcode = box(id=nid(), maxclass="codebox", code=code, numinlets=2, numoutlets=2, outlettype=["", ""],
                patching_rect=[30, 80, 700, 400], fontname="Menlo", fontsize=11.0)
    gout = [box(id=nid(), maxclass="newobj", text=f"out {i}", numinlets=1, numoutlets=0, patching_rect=[30 + 80 * (i - 1), 520, 40, 22]) for i in (1, 2)]
    gboxes = [{"box": b["box"]} for b in gin + [gcode] + gout]
    glines = []
    for i in range(2):
        glines.append({"patchline": {"destination": [gcode["box"]["id"], i], "source": [gin[i]["box"]["id"], 0]}})
        glines.append({"patchline": {"destination": [gout[i]["box"]["id"], 0], "source": [gcode["box"]["id"], i]}})
    if thru:
        gboxes = [b for b in gboxes if b["box"].get("maxclass") != "codebox"]
        glines = [{"patchline": {"destination": [gout[i]["box"]["id"], 0], "source": [gin[i]["box"]["id"], 0]}} for i in range(2)]
    gen_patcher = {
        "fileversion": 1,
        "appversion": {"major": 8, "minor": 6, "revision": 2, "architecture": "x64", "modernui": 1},
        "classnamespace": "dsp.gen",
        "rect": [100.0, 100.0, 800.0, 600.0],
        "bglocked": 0, "openinpresentation": 0, "default_fontsize": 12.0, "default_fontface": 0,
        "default_fontname": "Arial", "gridonopen": 1, "gridsize": [15.0, 15.0], "gridsnaponopen": 1,
        "objectsnaponopen": 1, "statusbarvisible": 2, "toolbarvisible": 1, "lefttoolbarpinned": 0,
        "toptoolbarpinned": 0, "righttoolbarpinned": 0, "bottomtoolbarpinned": 0, "toolbars_unpinned_last_save": 0,
        "tallnewobj": 0, "boxanimatetime": 200, "enablehscroll": 1, "enablevscroll": 1, "devicewidth": 0.0,
        "description": "", "digest": "", "tags": "", "style": "", "subpatcher_template": "",
        "assistshowspatchername": 0, "boxes": gboxes, "lines": glines,
    }

    plugin = add(box(id=nid(), maxclass="newobj", text="plugin~", numinlets=2, numoutlets=2, outlettype=["signal", "signal"], patching_rect=[30, 340, 60, 22]))
    gen = add(box(id=nid(), maxclass="newobj", text="gen~", numinlets=2, numoutlets=2, outlettype=["signal", "signal"],
                  patching_rect=[30, 400, 60, 22], patcher=gen_patcher))
    plugout = add(box(id=nid(), maxclass="newobj", text="plugout~", numinlets=2, numoutlets=0, patching_rect=[30, 460, 70, 22]))
    for i in range(2):
        line(plugin, i, gen, i)
        line(gen, i, plugout, i)
    if not ui:
        add(box(id=nid(), maxclass="comment", text=("AGE12 pass-through test:\nshould sound unchanged" if thru else "AGE12 DSP test (no controls):\nSP-1200, +12 st, Mix 100 %"), presentation=1,
                presentation_rect=[8.0, 6.0, 200.0, 34.0], patching_rect=[150, 340, 200, 34], fontsize=12.0))
        return finish(boxes, lines, 220.0, "AGE·12 DSP-only test device")

    # ---- presentation layout
    add(box(id=nid(), maxclass="comment", text="AGE·12  —  real-time sample ager", presentation=1,
            presentation_rect=[8.0, 6.0, 190.0, 20.0], patching_rect=[300, 20, 200, 20], fontsize=12.0, fontface=1))

    dial_ids = {}
    def dial_rect(i, row):
        return [8.0 + 50.0 * i, 30.0 + 62.0 * row, 44.0, 48.0]
    layout = {"pitchst": (0, 0), "crushrate": (1, 0), "bitdepth": (2, 0), "prefilt": (3, 0), "dacfreq": (4, 0),
              "dacres": (5, 0), "satur": (6, 0), "noiselvl": (7, 0), "asymm": (0, 1), "wetmix": (1, 1)}
    y0 = 100
    for n, (name, longn, short, mn, mx, init, unit, typ) in enumerate(PARAMS):
        col, row = layout[name]
        d = add(box(id=nid(), maxclass="live.dial", numinlets=1, numoutlets=2, outlettype=["", "float"], parameter_enable=1,
                    patching_rect=[300 + 70 * n, y0, 44.0, 48.0], presentation=1, presentation_rect=dial_rect(col, row),
                    varname=longn.replace(" ", ""),
                    saved_attribute_attributes={"valueof": {"parameter_initial": [init], "parameter_initial_enable": 1,
                        "parameter_longname": longn, "parameter_mmax": float(mx), "parameter_mmin": float(mn),
                        "parameter_shortname": short, "parameter_type": typ, "parameter_unitstyle": unit}}))
        dial_ids[name] = d
        p = add(box(id=nid(), maxclass="newobj", text=f"prepend {name}", numinlets=1, numoutlets=1, outlettype=[""],
                    patching_rect=[300 + 70 * n, y0 + 70, 100, 22]))
        line(d, 0, p, 0)
        line(p, 0, gen, 0)

    tg = add(box(id=nid(), maxclass="live.toggle", numinlets=1, numoutlets=1, outlettype=[""], parameter_enable=1,
                 patching_rect=[300, y0 + 120, 24, 24], presentation=1, presentation_rect=[110.0, 96.0, 20.0, 20.0],
                 varname="Companded",
                 saved_attribute_attributes={"valueof": {"parameter_enum": ["linear", "companded"], "parameter_initial": [0],
                     "parameter_initial_enable": 1, "parameter_longname": "Companded", "parameter_mmax": 1,
                     "parameter_shortname": "Comp", "parameter_type": 2}}))
    tp = add(box(id=nid(), maxclass="newobj", text="prepend companded", numinlets=1, numoutlets=1, outlettype=[""], patching_rect=[340, y0 + 120, 110, 22]))
    line(tg, 0, tp, 0); line(tp, 0, gen, 0)
    add(box(id=nid(), maxclass="comment", text="MPC-style\ncompanded quantiser", presentation=1,
            presentation_rect=[134.0, 92.0, 140.0, 30.0], patching_rect=[480, y0 + 120, 120, 30], fontsize=10.0))

    # ---- model presets: button -> message -> unpack -> dials
    order = ["crushrate", "bitdepth", "prefilt", "dacfreq", "dacres", "satur", "noiselvl", "asymm"]
    unp = add(box(id=nid(), maxclass="newobj", text="unpack " + " ".join(["0."] * (len(order) + 1)), numinlets=1,
                  numoutlets=len(order) + 1, outlettype=[""] * (len(order) + 1), patching_rect=[30, 250, 400, 22]))
    for i, nm in enumerate(order):
        line(unp, i, dial_ids[nm], 0)
    line(unp, len(order), tg, 0)
    for n, (label, pr) in enumerate(PRESETS.items()):
        msg = add(box(id=nid(), maxclass="message", text=" ".join(str(pr[k]) for k in order + ["comp"]), numinlets=2, numoutlets=1,
                      outlettype=[""], patching_rect=[30, 130 + 30 * n, 380, 22]))
        btn = add(box(id=nid(), maxclass="textbutton", text=label, numinlets=1, numoutlets=3, outlettype=["", "", "int"],
                      patching_rect=[450, 130 + 30 * n, 70, 22], presentation=1,
                      presentation_rect=[200.0 + 68.0 * n, 6.0, 64.0, 20.0], mode=0))
        line(btn, 0, msg, 0)
        line(msg, 0, unp, 0)

    return finish(boxes, lines, 420.0, "AGE·12 real-time sample ager (SP-1200 / MPC60 / MPC3000)")

def amxd_bytes(doc):
    body = (json.dumps(doc, indent=2, ensure_ascii=False) + "\n").encode("utf-8")
    return (b"ampf" + struct.pack("<I", 4) + b"aaaa" +
            b"meta" + struct.pack("<I", 4) + b"\x00\x00\x00\x00" +
            b"ptch" + struct.pack("<I", len(body)) + body)

if __name__ == "__main__":
    code = genexpr()
    open("AGE12.genexpr", "w").write(code)
    doc = build_patcher(code)
    open("AGE12.maxpat", "w").write(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")
    open("AGE12.amxd", "wb").write(amxd_bytes(doc))
    _id[0] = 0
    open("AGE12_min.amxd", "wb").write(amxd_bytes(build_patcher(code, ui=False)))
    _id[0] = 0
    open("AGE12_thru.amxd", "wb").write(amxd_bytes(build_patcher(code, ui=False, thru=True)))
    json.loads(open("AGE12.maxpat").read())  # sanity: valid JSON
    print("wrote AGE12.genexpr, AGE12.maxpat, AGE12.amxd, AGE12_min.amxd, AGE12_thru.amxd")
