{
  "patcher": {
    "fileversion": 1,
    "appversion": {
      "major": 8,
      "minor": 6,
      "revision": 2,
      "architecture": "x64",
      "modernui": 1
    },
    "classnamespace": "box",
    "rect": [
      100.0,
      100.0,
      900.0,
      640.0
    ],
    "bglocked": 0,
    "openinpresentation": 1,
    "default_fontsize": 12.0,
    "default_fontface": 0,
    "default_fontname": "Arial",
    "gridonopen": 1,
    "gridsize": [
      15.0,
      15.0
    ],
    "gridsnaponopen": 1,
    "objectsnaponopen": 1,
    "statusbarvisible": 2,
    "toolbarvisible": 1,
    "lefttoolbarpinned": 0,
    "toptoolbarpinned": 0,
    "righttoolbarpinned": 0,
    "bottomtoolbarpinned": 0,
    "toolbars_unpinned_last_save": 0,
    "tallnewobj": 0,
    "boxanimatetime": 200,
    "enablehscroll": 1,
    "enablevscroll": 1,
    "devicewidth": 562.0,
    "description": "VINK·LOOP recursive feedback network (ring mod + filter + tape saturation + delay)",
    "digest": "",
    "tags": "",
    "style": "",
    "subpatcher_template": "",
    "assistshowspatchername": 0,
    "boxes": [
      {
        "box": {
          "id": "obj-6",
          "maxclass": "newobj",
          "text": "plugin~",
          "numinlets": 2,
          "numoutlets": 2,
          "outlettype": [
            "signal",
            "signal"
          ],
          "patching_rect": [
            30,
            340,
            60,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-7",
          "maxclass": "newobj",
          "text": "gen~",
          "numinlets": 2,
          "numoutlets": 2,
          "outlettype": [
            "signal",
            "signal"
          ],
          "patching_rect": [
            30,
            400,
            60,
            22
          ],
          "patcher": {
            "fileversion": 1,
            "appversion": {
              "major": 8,
              "minor": 6,
              "revision": 2,
              "architecture": "x64",
              "modernui": 1
            },
            "classnamespace": "dsp.gen",
            "rect": [
              100.0,
              100.0,
              800.0,
              600.0
            ],
            "bglocked": 0,
            "openinpresentation": 0,
            "default_fontsize": 12.0,
            "default_fontface": 0,
            "default_fontname": "Arial",
            "gridonopen": 1,
            "gridsize": [
              15.0,
              15.0
            ],
            "gridsnaponopen": 1,
            "objectsnaponopen": 1,
            "statusbarvisible": 2,
            "toolbarvisible": 1,
            "lefttoolbarpinned": 0,
            "toptoolbarpinned": 0,
            "righttoolbarpinned": 0,
            "bottomtoolbarpinned": 0,
            "toolbars_unpinned_last_save": 0,
            "tallnewobj": 0,
            "boxanimatetime": 200,
            "enablehscroll": 1,
            "enablevscroll": 1,
            "devicewidth": 0.0,
            "description": "",
            "digest": "",
            "tags": "",
            "style": "",
            "subpatcher_template": "",
            "assistshowspatchername": 0,
            "boxes": [
              {
                "box": {
                  "id": "obj-1",
                  "maxclass": "newobj",
                  "text": "in 1",
                  "numinlets": 0,
                  "numoutlets": 1,
                  "outlettype": [
                    ""
                  ],
                  "patching_rect": [
                    30,
                    30,
                    40,
                    22
                  ]
                }
              },
              {
                "box": {
                  "id": "obj-2",
                  "maxclass": "newobj",
                  "text": "in 2",
                  "numinlets": 0,
                  "numoutlets": 1,
                  "outlettype": [
                    ""
                  ],
                  "patching_rect": [
                    110,
                    30,
                    40,
                    22
                  ]
                }
              },
              {
                "box": {
                  "id": "obj-3",
                  "maxclass": "codebox",
                  "code": "// VINK-LOOP: recursive feedback network (ring modulator + filters + tape saturation + delay in a closed loop), stereo.\n// Generated by build_vink.py - edit there, not here.\nParam seedlvl(0.5, min=0, max=1);          // how much of the track audio seeds the loop\nParam nfloor(0.25, min=0, max=1);          // noise floor injected into the loop (self-start)\nParam fbk(1.3, min=0, max=1.5);            // loop gain; ring mod + filters lose energy, so the loop only holds from about 1.2 (measured, see test)\nParam ringd(0.5, min=0, max=1);            // ring modulator depth\nParam cfreq(55, min=0.5, max=2000);        // carrier oscillator Hz\nParam cwave(0, min=0, max=7);              // carrier: 0 sine, 1 triangle, 2 saw, 3 square, 4 sample-and-hold, 5 smooth random, 6 noise, 7 cross-feed (2nd delay tap)\nParam hpf(80, min=20, max=400);\nParam lpf(8000, min=1000, max=16000);\nParam satur(0.4, min=0, max=1);\nParam dtime(180, min=20, max=500);         // ms\nParam wow(0.25, min=0, max=1);\nParam spread(0.3, min=0, max=1);\nParam level(0.5, min=0, max=1);\nParam wetmix(1, min=0, max=1);\nParam burst(0, min=0, max=1);              // 1 = inject a noise burst (button holds it ~120 ms)\nParam clear(0, min=0, max=1);              // 1 = RESET: silence the loop and zero delay + filter memory (button holds it ~750 ms)\n\nHistory phAL(0); History phBL(0); History nzL(0); History cphL(0); History wL(0);\nHistory hs1L(0); History hs2L(0); History ls1L(0); History ls2L(0);\nHistory shL(0); History saL(0); History sbL(0);\nData dbL(131072);\nHistory phAR(0); History phBR(0); History nzR(0); History cphR(0); History wR(0);\nHistory hs1R(0); History hs2R(0); History ls1R(0); History ls2R(0);\nHistory shR(0); History saR(0); History sbR(0);\nData dbR(131072);\n\n// ---- parameters, clamped so that unset/zero values can never produce inf or NaN ----\nsl = max(0, min(1, seedlvl));\nnzp = max(0, min(1, nfloor));\nnf = nzp * nzp * 0.05;\nfbk2 = max(0, min(1.5, fbk));\nrd = max(0, min(1, ringd));\ncf = max(0.5, min(2000, cfreq));\nwv = max(0, min(7, floor(cwave + 0.5)));\nk0 = wv < 0.5;\nk1 = (wv > 0.5) * (wv < 1.5);\nk2 = (wv > 1.5) * (wv < 2.5);\nk3 = (wv > 2.5) * (wv < 3.5);\nk4 = (wv > 3.5) * (wv < 4.5);\nk5 = (wv > 4.5) * (wv < 5.5);\nk6 = (wv > 5.5) * (wv < 6.5);\nk7 = wv > 6.5;\n// mean square of each carrier (for the power normalisation of the ring modulator)\ncpow = 0.5 * k0 + 0.3333 * k1 + 0.3333 * k2 + 1 * k3 + 0.3333 * k4 + 0.2 * k5 + 0.3333 * k6 + 0.5 * k7;\nrde = rd * (1 - k7) + min(rd, 0.85) * k7;   // cross-feed: pure product with its own delayed tap would die, so RING is capped there\nrnorm = 1 / sqrt((1 - rde) * (1 - rde) + cpow * rde * rde);\nhpa = 1 - exp(-6.283185307179586 * max(20, min(400, hpf)) / samplerate);\nlpa = 1 - exp(-6.283185307179586 * max(1000, min(16000, lpf)) / samplerate);\ndrv = 1 + 5 * max(0, min(1, satur));\ntau = max(20, min(500, dtime)) * 0.001 * samplerate;\nwowd = max(0, min(1, wow));\nspr = max(0, min(1, spread));\nlvl = max(0, min(1, level));\nwmx = max(0, min(1, wetmix));\nbg = max(0, min(1, burst));\nkeep = 1 - max(0, min(1, clear));\n\n// ================= channel L =================\n// wow / flutter / random drift on the delay time\nphAL = phAL + 0.45 / samplerate; phAL = phAL - floor(phAL);\nphBL = phBL + 5.3 / samplerate;  phBL = phBL - floor(phBL);\nnzL = nzL + 0.0005 * (noise() - nzL);\nwmL = wowd * (0.02 * sin(6.283185307179586 * phAL) + 0.006 * sin(6.283185307179586 * phBL) + 0.09 * nzL);\ntdL = tau * 1 * (1 + wmL);\ntdL = max(64, min(131072 - 8, tdL));\n// two taps of the delay line (read before this sample is written); RESET (keep = 0) silences them at once\nrpL = wL - tdL;\nif (rpL < 0) { rpL = rpL + 131072; }\ni0L = floor(rpL); frL = rpL - i0L;\nxL = (peek(dbL, mod(i0L, 131072)) * (1 - frL) + peek(dbL, mod(i0L + 1, 131072)) * frL) * keep;\nrqL = wL - tdL * 0.618;\nif (rqL < 0) { rqL = rqL + 131072; }\nj0L = floor(rqL); fqL = rqL - j0L;\nx2L = (peek(dbL, mod(j0L, 131072)) * (1 - fqL) + peek(dbL, mod(j0L + 1, 131072)) * fqL) * keep;\n// carrier: one phase, all waveforms computed, selected by the weights k0..k7 (no if-blocks: GenExpr scoping)\npoL = cphL;\ncphL = cphL + cf * 1 / samplerate; cphL = cphL - floor(cphL);\nwrL = cphL < poL;                                  // 1 on the sample where the phase wraps\nshL = shL + wrL * (noise() - shL);               // sample & hold: new random value at each wrap\nsaL = saL + wrL * (sbL - saL);                 // smooth random: glide from the old to the new value\nsbL = sbL + wrL * (noise() - sbL);\ncSL = sin(6.283185307179586 * cphL);\ncTL = 1 - 4 * abs(cphL - 0.5);\ncWL = 2 * cphL - 1;\ncQL = 1 - 2 * (cphL > 0.5);\ncML = saL + (sbL - saL) * cphL * cphL * (3 - 2 * cphL);\ncXL = 0.15 + 0.85 * tanh(3 * drv * x2L);            // cross-feed; 0.15 = leak of an unbalanced ring modulator, lets the loop start\ncarL = k0 * cSL + k1 * cTL + k2 * cWL + k3 * cQL + k4 * shL + k5 * cML + k6 * noise() + k7 * cXL;\n// mixer / hub: seed + noise floor + burst + feedback\nhubL = (in1 * sl + fbk2 * xL + nf * noise() + bg * 0.3 * noise() + 0.0000000001 * noise()) * keep;\n// ring modulator (blend: 0 = bypass, 1 = pure multiplication), power-normalised so that FEEDBACK 1.0 stays the unity point\nrmoL = hubL * (1 - rde + rde * carL) * rnorm;\n// 2-pole high-pass, 2-pole low-pass (states are cleared by RESET)\nhs1L = (hs1L + hpa * (rmoL - hs1L)) * keep; vvL = rmoL - hs1L;\nhs2L = (hs2L + hpa * (vvL - hs2L)) * keep;  vvL = vvL - hs2L;\nls1L = (ls1L + lpa * (vvL - ls1L)) * keep;\nls2L = (ls2L + lpa * (ls1L - ls2L)) * keep;\n// tape saturation: soft limiter with unity small-signal gain, peak 1/drive\nsvL = tanh(drv * ls2L) / drv;\npoke(dbL, svL * keep, wL);\nwL = mod(wL + 1, 131072);\n// output tap = delay output; x <= 1/drive, so wet <= level\nout1 = in1 * (1 - wmx) + xL * drv * lvl * wmx;\n\n// ================= channel R =================\n// wow / flutter / random drift on the delay time\nphAR = phAR + 0.45 / samplerate; phAR = phAR - floor(phAR);\nphBR = phBR + 5.3 / samplerate;  phBR = phBR - floor(phBR);\nnzR = nzR + 0.0005 * (noise() - nzR);\nwmR = wowd * (0.02 * sin(6.283185307179586 * phAR) + 0.006 * sin(6.283185307179586 * phBR) + 0.09 * nzR);\ntdR = tau * (1 + 0.07 * spr) * (1 + wmR);\ntdR = max(64, min(131072 - 8, tdR));\n// two taps of the delay line (read before this sample is written); RESET (keep = 0) silences them at once\nrpR = wR - tdR;\nif (rpR < 0) { rpR = rpR + 131072; }\ni0R = floor(rpR); frR = rpR - i0R;\nxR = (peek(dbR, mod(i0R, 131072)) * (1 - frR) + peek(dbR, mod(i0R + 1, 131072)) * frR) * keep;\nrqR = wR - tdR * 0.618;\nif (rqR < 0) { rqR = rqR + 131072; }\nj0R = floor(rqR); fqR = rqR - j0R;\nx2R = (peek(dbR, mod(j0R, 131072)) * (1 - fqR) + peek(dbR, mod(j0R + 1, 131072)) * fqR) * keep;\n// carrier: one phase, all waveforms computed, selected by the weights k0..k7 (no if-blocks: GenExpr scoping)\npoR = cphR;\ncphR = cphR + cf * (1 + 0.013 * spr) / samplerate; cphR = cphR - floor(cphR);\nwrR = cphR < poR;                                  // 1 on the sample where the phase wraps\nshR = shR + wrR * (noise() - shR);               // sample & hold: new random value at each wrap\nsaR = saR + wrR * (sbR - saR);                 // smooth random: glide from the old to the new value\nsbR = sbR + wrR * (noise() - sbR);\ncSR = sin(6.283185307179586 * cphR);\ncTR = 1 - 4 * abs(cphR - 0.5);\ncWR = 2 * cphR - 1;\ncQR = 1 - 2 * (cphR > 0.5);\ncMR = saR + (sbR - saR) * cphR * cphR * (3 - 2 * cphR);\ncXR = 0.15 + 0.85 * tanh(3 * drv * x2R);            // cross-feed; 0.15 = leak of an unbalanced ring modulator, lets the loop start\ncarR = k0 * cSR + k1 * cTR + k2 * cWR + k3 * cQR + k4 * shR + k5 * cMR + k6 * noise() + k7 * cXR;\n// mixer / hub: seed + noise floor + burst + feedback\nhubR = (in2 * sl + fbk2 * xR + nf * noise() + bg * 0.3 * noise() + 0.0000000001 * noise()) * keep;\n// ring modulator (blend: 0 = bypass, 1 = pure multiplication), power-normalised so that FEEDBACK 1.0 stays the unity point\nrmoR = hubR * (1 - rde + rde * carR) * rnorm;\n// 2-pole high-pass, 2-pole low-pass (states are cleared by RESET)\nhs1R = (hs1R + hpa * (rmoR - hs1R)) * keep; vvR = rmoR - hs1R;\nhs2R = (hs2R + hpa * (vvR - hs2R)) * keep;  vvR = vvR - hs2R;\nls1R = (ls1R + lpa * (vvR - ls1R)) * keep;\nls2R = (ls2R + lpa * (ls1R - ls2R)) * keep;\n// tape saturation: soft limiter with unity small-signal gain, peak 1/drive\nsvR = tanh(drv * ls2R) / drv;\npoke(dbR, svR * keep, wR);\nwR = mod(wR + 1, 131072);\n// output tap = delay output; x <= 1/drive, so wet <= level\nout2 = in2 * (1 - wmx) + xR * drv * lvl * wmx;\n",
                  "numinlets": 2,
                  "numoutlets": 2,
                  "outlettype": [
                    "",
                    ""
                  ],
                  "patching_rect": [
                    30,
                    80,
                    700,
                    400
                  ],
                  "fontname": "Menlo",
                  "fontsize": 11.0
                }
              },
              {
                "box": {
                  "id": "obj-4",
                  "maxclass": "newobj",
                  "text": "out 1",
                  "numinlets": 1,
                  "numoutlets": 0,
                  "patching_rect": [
                    30,
                    520,
                    40,
                    22
                  ]
                }
              },
              {
                "box": {
                  "id": "obj-5",
                  "maxclass": "newobj",
                  "text": "out 2",
                  "numinlets": 1,
                  "numoutlets": 0,
                  "patching_rect": [
                    110,
                    520,
                    40,
                    22
                  ]
                }
              }
            ],
            "lines": [
              {
                "patchline": {
                  "destination": [
                    "obj-3",
                    0
                  ],
                  "source": [
                    "obj-1",
                    0
                  ]
                }
              },
              {
                "patchline": {
                  "destination": [
                    "obj-4",
                    0
                  ],
                  "source": [
                    "obj-3",
                    0
                  ]
                }
              },
              {
                "patchline": {
                  "destination": [
                    "obj-3",
                    1
                  ],
                  "source": [
                    "obj-2",
                    0
                  ]
                }
              },
              {
                "patchline": {
                  "destination": [
                    "obj-5",
                    0
                  ],
                  "source": [
                    "obj-3",
                    1
                  ]
                }
              }
            ]
          }
        }
      },
      {
        "box": {
          "id": "obj-8",
          "maxclass": "newobj",
          "text": "plugout~",
          "numinlets": 2,
          "numoutlets": 0,
          "patching_rect": [
            30,
            460,
            70,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-11",
          "maxclass": "comment",
          "text": "SEED",
          "textcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "fontname": "Arial",
          "fontsize": 8.0,
          "fontface": 1,
          "textjustification": 0,
          "presentation": 1,
          "presentation_rect": [
            14.0,
            8.0,
            90.0,
            11.0
          ],
          "patching_rect": [
            814.0,
            28.0,
            90.0,
            11.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-13",
          "maxclass": "comment",
          "text": "MIXER",
          "textcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "fontname": "Arial",
          "fontsize": 8.0,
          "fontface": 1,
          "textjustification": 0,
          "presentation": 1,
          "presentation_rect": [
            124.0,
            8.0,
            46.0,
            11.0
          ],
          "patching_rect": [
            924.0,
            28.0,
            46.0,
            11.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-15",
          "maxclass": "comment",
          "text": "RING MOD",
          "textcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "fontname": "Arial",
          "fontsize": 8.0,
          "fontface": 1,
          "textjustification": 0,
          "presentation": 1,
          "presentation_rect": [
            190.0,
            8.0,
            90.0,
            11.0
          ],
          "patching_rect": [
            990.0,
            28.0,
            90.0,
            11.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-17",
          "maxclass": "comment",
          "text": "FILTER",
          "textcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "fontname": "Arial",
          "fontsize": 8.0,
          "fontface": 1,
          "textjustification": 0,
          "presentation": 1,
          "presentation_rect": [
            300.0,
            8.0,
            90.0,
            11.0
          ],
          "patching_rect": [
            1100.0,
            28.0,
            90.0,
            11.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-19",
          "maxclass": "comment",
          "text": "TAPE / DELAY",
          "textcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "fontname": "Arial",
          "fontsize": 8.0,
          "fontface": 1,
          "textjustification": 0,
          "presentation": 1,
          "presentation_rect": [
            410.0,
            8.0,
            138.0,
            11.0
          ],
          "patching_rect": [
            1210.0,
            28.0,
            138.0,
            11.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-21",
          "maxclass": "comment",
          "text": "OUT",
          "textcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "fontname": "Arial",
          "fontsize": 8.0,
          "fontface": 1,
          "textjustification": 0,
          "presentation": 1,
          "presentation_rect": [
            300.0,
            86.0,
            40.0,
            11.0
          ],
          "patching_rect": [
            1100.0,
            106.0,
            40.0,
            11.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-22",
          "maxclass": "comment",
          "text": ">",
          "textcolor": [
            1.0,
            0.5882,
            0.3765,
            1.0
          ],
          "fontname": "Arial",
          "fontsize": 12.0,
          "fontface": 1,
          "textjustification": 1,
          "presentation": 1,
          "presentation_rect": [
            110.0,
            62.0,
            12.0,
            14.0
          ],
          "patching_rect": [
            910.0,
            82.0,
            12.0,
            14.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-23",
          "maxclass": "comment",
          "text": ">",
          "textcolor": [
            1.0,
            0.5882,
            0.3765,
            1.0
          ],
          "fontname": "Arial",
          "fontsize": 12.0,
          "fontface": 1,
          "textjustification": 1,
          "presentation": 1,
          "presentation_rect": [
            176.0,
            62.0,
            12.0,
            14.0
          ],
          "patching_rect": [
            976.0,
            82.0,
            12.0,
            14.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-24",
          "maxclass": "comment",
          "text": ">",
          "textcolor": [
            1.0,
            0.5882,
            0.3765,
            1.0
          ],
          "fontname": "Arial",
          "fontsize": 12.0,
          "fontface": 1,
          "textjustification": 1,
          "presentation": 1,
          "presentation_rect": [
            286.0,
            62.0,
            12.0,
            14.0
          ],
          "patching_rect": [
            1086.0,
            82.0,
            12.0,
            14.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-25",
          "maxclass": "comment",
          "text": ">",
          "textcolor": [
            1.0,
            0.5882,
            0.3765,
            1.0
          ],
          "fontname": "Arial",
          "fontsize": 12.0,
          "fontface": 1,
          "textjustification": 1,
          "presentation": 1,
          "presentation_rect": [
            396.0,
            62.0,
            12.0,
            14.0
          ],
          "patching_rect": [
            1196.0,
            82.0,
            12.0,
            14.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-27",
          "maxclass": "comment",
          "text": "<<<<<<   RECURSIVE RETURN:  delay out  x feedback  >>  mixer   <<<<<<",
          "textcolor": [
            1.0,
            0.5882,
            0.3765,
            1.0
          ],
          "fontname": "Arial",
          "fontsize": 7.0,
          "fontface": 1,
          "textjustification": 1,
          "presentation": 1,
          "presentation_rect": [
            8.0,
            152.0,
            546.0,
            10.0
          ],
          "patching_rect": [
            808.0,
            172.0,
            546.0,
            10.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-28",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            300,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            14.0,
            22.0,
            46.0,
            56.0
          ],
          "varname": "SeedInput",
          "fontname": "Arial",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.2275,
            0.2745,
            0.3451,
            1.0
          ],
          "activedialcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "needlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "activeneedlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "textcolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                0.5
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Seed Input",
              "parameter_mmax": 1.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Seed",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-29",
          "maxclass": "newobj",
          "text": "prepend seedlvl",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            300,
            160,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-30",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            370,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            62.0,
            22.0,
            46.0,
            56.0
          ],
          "varname": "NoiseFloor",
          "fontname": "Arial",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.2275,
            0.2745,
            0.3451,
            1.0
          ],
          "activedialcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "needlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "activeneedlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "textcolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                0.25
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Noise Floor",
              "parameter_mmax": 1.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Noise",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-31",
          "maxclass": "newobj",
          "text": "prepend nfloor",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            370,
            160,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-32",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            440,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            123.0,
            22.0,
            46.0,
            56.0
          ],
          "varname": "Feedback",
          "fontname": "Arial",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.2275,
            0.2745,
            0.3451,
            1.0
          ],
          "activedialcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "needlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "activeneedlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "textcolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                1.3
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Feedback",
              "parameter_mmax": 1.5,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Fdbk",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-33",
          "maxclass": "newobj",
          "text": "prepend fbk",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            440,
            160,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-34",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            510,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            190.0,
            22.0,
            46.0,
            56.0
          ],
          "varname": "RingDepth",
          "fontname": "Arial",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.2275,
            0.2745,
            0.3451,
            1.0
          ],
          "activedialcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "needlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "activeneedlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "textcolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                0.5
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Ring Depth",
              "parameter_mmax": 1.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Ring",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-35",
          "maxclass": "newobj",
          "text": "prepend ringd",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            510,
            160,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-36",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            580,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            238.0,
            22.0,
            46.0,
            56.0
          ],
          "varname": "Carrier",
          "fontname": "Arial",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.2275,
            0.2745,
            0.3451,
            1.0
          ],
          "activedialcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "needlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "activeneedlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "textcolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                55.0
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Carrier",
              "parameter_mmax": 2000.0,
              "parameter_mmin": 0.5,
              "parameter_shortname": "Carr",
              "parameter_type": 0,
              "parameter_unitstyle": 3,
              "parameter_exponent": 3.0
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-37",
          "maxclass": "newobj",
          "text": "prepend cfreq",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            580,
            160,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-38",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            650,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            300.0,
            22.0,
            46.0,
            56.0
          ],
          "varname": "LowCut",
          "fontname": "Arial",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.2275,
            0.2745,
            0.3451,
            1.0
          ],
          "activedialcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "needlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "activeneedlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "textcolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                80.0
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Low Cut",
              "parameter_mmax": 400.0,
              "parameter_mmin": 20.0,
              "parameter_shortname": "LoCut",
              "parameter_type": 0,
              "parameter_unitstyle": 3,
              "parameter_exponent": 3.0
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-39",
          "maxclass": "newobj",
          "text": "prepend hpf",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            650,
            160,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-40",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            720,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            348.0,
            22.0,
            46.0,
            56.0
          ],
          "varname": "HighCut",
          "fontname": "Arial",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.2275,
            0.2745,
            0.3451,
            1.0
          ],
          "activedialcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "needlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "activeneedlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "textcolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                8000.0
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "High Cut",
              "parameter_mmax": 16000.0,
              "parameter_mmin": 1000.0,
              "parameter_shortname": "HiCut",
              "parameter_type": 0,
              "parameter_unitstyle": 3,
              "parameter_exponent": 3.0
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-41",
          "maxclass": "newobj",
          "text": "prepend lpf",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            720,
            160,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-42",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            790,
            100,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            410.0,
            22.0,
            46.0,
            56.0
          ],
          "varname": "TapeDrive",
          "fontname": "Arial",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.2275,
            0.2745,
            0.3451,
            1.0
          ],
          "activedialcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "needlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "activeneedlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "textcolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                0.4
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Tape Drive",
              "parameter_mmax": 1.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Drive",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-43",
          "maxclass": "newobj",
          "text": "prepend satur",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            790,
            160,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-44",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            300,
            210,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            458.0,
            22.0,
            46.0,
            56.0
          ],
          "varname": "DelayTime",
          "fontname": "Arial",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.2275,
            0.2745,
            0.3451,
            1.0
          ],
          "activedialcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "needlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "activeneedlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "textcolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                180.0
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Delay Time",
              "parameter_mmax": 500.0,
              "parameter_mmin": 20.0,
              "parameter_shortname": "Delay",
              "parameter_type": 0,
              "parameter_unitstyle": 2,
              "parameter_exponent": 2.0
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-45",
          "maxclass": "newobj",
          "text": "prepend dtime",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            300,
            270,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-46",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            370,
            210,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            506.0,
            22.0,
            46.0,
            56.0
          ],
          "varname": "WowFlutter",
          "fontname": "Arial",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.2275,
            0.2745,
            0.3451,
            1.0
          ],
          "activedialcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "needlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "activeneedlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "textcolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                0.25
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Wow Flutter",
              "parameter_mmax": 1.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Wow",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-47",
          "maxclass": "newobj",
          "text": "prepend wow",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            370,
            270,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-48",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            440,
            210,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            330.0,
            88.0,
            46.0,
            56.0
          ],
          "varname": "StereoSpread",
          "fontname": "Arial",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.2275,
            0.2745,
            0.3451,
            1.0
          ],
          "activedialcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "needlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "activeneedlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "textcolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                0.3
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Stereo Spread",
              "parameter_mmax": 1.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Sprd",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-49",
          "maxclass": "newobj",
          "text": "prepend spread",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            440,
            270,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-50",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            510,
            210,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            398.0,
            88.0,
            46.0,
            56.0
          ],
          "varname": "OutputLevel",
          "fontname": "Arial",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.2275,
            0.2745,
            0.3451,
            1.0
          ],
          "activedialcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "needlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "activeneedlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "textcolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                0.5
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Output Level",
              "parameter_mmax": 1.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Level",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-51",
          "maxclass": "newobj",
          "text": "prepend level",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            510,
            270,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-52",
          "maxclass": "live.dial",
          "numinlets": 1,
          "numoutlets": 2,
          "outlettype": [
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            580,
            210,
            44.0,
            48.0
          ],
          "presentation": 1,
          "presentation_rect": [
            466.0,
            88.0,
            46.0,
            56.0
          ],
          "varname": "Mix",
          "fontname": "Arial",
          "fontsize": 9.0,
          "fontface": 1,
          "dialcolor": [
            0.2275,
            0.2745,
            0.3451,
            1.0
          ],
          "activedialcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "needlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "activeneedlecolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "textcolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_initial": [
                1.0
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Mix",
              "parameter_mmax": 1.0,
              "parameter_mmin": 0.0,
              "parameter_shortname": "Mix",
              "parameter_type": 0,
              "parameter_unitstyle": 1
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-53",
          "maxclass": "newobj",
          "text": "prepend wetmix",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            580,
            270,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-54",
          "maxclass": "live.menu",
          "numinlets": 1,
          "numoutlets": 3,
          "outlettype": [
            "",
            "",
            "float"
          ],
          "parameter_enable": 1,
          "patching_rect": [
            30,
            300,
            100,
            20
          ],
          "presentation": 1,
          "presentation_rect": [
            190.0,
            100.0,
            92.0,
            18.0
          ],
          "varname": "CarrierWave",
          "fontname": "Arial",
          "fontsize": 9.0,
          "fontface": 1,
          "textcolor": [
            0.8627,
            0.8941,
            0.9255,
            1.0
          ],
          "bgcolor": [
            0.1412,
            0.1725,
            0.2196,
            1.0
          ],
          "bordercolor": [
            0.2902,
            0.3451,
            0.4235,
            1.0
          ],
          "activebgcolor": [
            0.1412,
            0.1725,
            0.2196,
            1.0
          ],
          "activetextcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "hltcolor": [
            0.2353,
            0.3137,
            0.3843,
            1.0
          ],
          "saved_attribute_attributes": {
            "valueof": {
              "parameter_enum": [
                "SINE",
                "TRIANGLE",
                "SAW",
                "SQUARE",
                "SAMPLE & HOLD",
                "SMOOTH RANDOM",
                "NOISE",
                "CROSS-FEED"
              ],
              "parameter_initial": [
                0
              ],
              "parameter_initial_enable": 1,
              "parameter_longname": "Carrier Wave",
              "parameter_mmax": 7,
              "parameter_shortname": "Wave",
              "parameter_type": 2
            }
          }
        }
      },
      {
        "box": {
          "id": "obj-55",
          "maxclass": "newobj",
          "text": "prepend cwave",
          "numinlets": 1,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            150,
            300,
            100,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-56",
          "maxclass": "comment",
          "text": "carrier wave: S&H = stepped\nrandom at the CARR rate;\nCROSS-FEED = loop tap",
          "textcolor": [
            0.4784,
            0.5412,
            0.6118,
            1.0
          ],
          "fontname": "Arial",
          "fontsize": 6.5,
          "fontface": 0,
          "textjustification": 0,
          "presentation": 1,
          "presentation_rect": [
            190.0,
            120.0,
            94.0,
            28.0
          ],
          "patching_rect": [
            990.0,
            140.0,
            94.0,
            28.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-57",
          "maxclass": "textbutton",
          "text": "SEED BURST",
          "numinlets": 1,
          "numoutlets": 3,
          "outlettype": [
            "",
            "",
            "int"
          ],
          "patching_rect": [
            30,
            340,
            80,
            22
          ],
          "presentation": 1,
          "presentation_rect": [
            14.0,
            96.0,
            92.0,
            22.0
          ],
          "mode": 0,
          "fontname": "Arial",
          "fontsize": 10.0,
          "fontface": 1,
          "bgcolor": [
            0.1804,
            0.1098,
            0.0784,
            1.0
          ],
          "bgoncolor": [
            1.0,
            0.5882,
            0.3765,
            1.0
          ],
          "bordercolor": [
            1.0,
            0.5882,
            0.3765,
            1.0
          ],
          "textcolor": [
            1.0,
            0.5882,
            0.3765,
            1.0
          ],
          "textoncolor": [
            0.0471,
            0.0471,
            0.0549,
            1.0
          ],
          "usebgoncolor": 1,
          "rounded": 6.0
        }
      },
      {
        "box": {
          "id": "obj-58",
          "maxclass": "message",
          "text": "burst 1",
          "numinlets": 2,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            30,
            380,
            60,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-59",
          "maxclass": "newobj",
          "text": "delay 120",
          "numinlets": 2,
          "numoutlets": 1,
          "outlettype": [
            "bang"
          ],
          "patching_rect": [
            120,
            340,
            60,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-60",
          "maxclass": "message",
          "text": "burst 0",
          "numinlets": 2,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            120,
            380,
            60,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-61",
          "maxclass": "textbutton",
          "text": "RESET",
          "numinlets": 1,
          "numoutlets": 3,
          "outlettype": [
            "",
            "",
            "int"
          ],
          "patching_rect": [
            30,
            380,
            80,
            22
          ],
          "presentation": 1,
          "presentation_rect": [
            14.0,
            122.0,
            92.0,
            22.0
          ],
          "mode": 0,
          "fontname": "Arial",
          "fontsize": 10.0,
          "fontface": 1,
          "bgcolor": [
            0.0784,
            0.1333,
            0.1725,
            1.0
          ],
          "bgoncolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "bordercolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "textcolor": [
            0.4784,
            0.8941,
            0.8,
            1.0
          ],
          "textoncolor": [
            0.0471,
            0.0471,
            0.0549,
            1.0
          ],
          "usebgoncolor": 1,
          "rounded": 6.0
        }
      },
      {
        "box": {
          "id": "obj-62",
          "maxclass": "message",
          "text": "clear 1",
          "numinlets": 2,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            30,
            420,
            60,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-63",
          "maxclass": "newobj",
          "text": "delay 750",
          "numinlets": 2,
          "numoutlets": 1,
          "outlettype": [
            "bang"
          ],
          "patching_rect": [
            120,
            420,
            60,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-64",
          "maxclass": "message",
          "text": "clear 0",
          "numinlets": 2,
          "numoutlets": 1,
          "outlettype": [
            ""
          ],
          "patching_rect": [
            120,
            460,
            60,
            22
          ]
        }
      },
      {
        "box": {
          "id": "obj-65",
          "maxclass": "comment",
          "text": "raise until\nit sustains\n(about 1.2\nto 1.4)",
          "textcolor": [
            0.4784,
            0.5412,
            0.6118,
            1.0
          ],
          "fontname": "Arial",
          "fontsize": 7.0,
          "fontface": 0,
          "textjustification": 1,
          "presentation": 1,
          "presentation_rect": [
            122.0,
            100.0,
            52.0,
            48.0
          ],
          "patching_rect": [
            922.0,
            120.0,
            52.0,
            48.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-26",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.0784,
            0.098,
            0.1294,
            1.0
          ],
          "border": 1,
          "rounded": 4.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            808.0,
            171.0,
            546.0,
            12.0
          ],
          "presentation": 1,
          "presentation_rect": [
            8.0,
            151.0,
            546.0,
            12.0
          ],
          "bordercolor": [
            0.1725,
            0.2118,
            0.2667,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-20",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.0784,
            0.098,
            0.1294,
            1.0
          ],
          "border": 1,
          "rounded": 5.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1094.0,
            104.0,
            260.0,
            64.0
          ],
          "presentation": 1,
          "presentation_rect": [
            294.0,
            84.0,
            260.0,
            64.0
          ],
          "bordercolor": [
            0.1725,
            0.2118,
            0.2667,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-18",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.0784,
            0.098,
            0.1294,
            1.0
          ],
          "border": 1,
          "rounded": 5.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1204.0,
            26.0,
            150.0,
            74.0
          ],
          "presentation": 1,
          "presentation_rect": [
            404.0,
            6.0,
            150.0,
            74.0
          ],
          "bordercolor": [
            0.1725,
            0.2118,
            0.2667,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-16",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.0784,
            0.098,
            0.1294,
            1.0
          ],
          "border": 1,
          "rounded": 5.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            1094.0,
            26.0,
            102.0,
            74.0
          ],
          "presentation": 1,
          "presentation_rect": [
            294.0,
            6.0,
            102.0,
            74.0
          ],
          "bordercolor": [
            0.1725,
            0.2118,
            0.2667,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-14",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.0784,
            0.098,
            0.1294,
            1.0
          ],
          "border": 1,
          "rounded": 5.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            984.0,
            26.0,
            102.0,
            142.0
          ],
          "presentation": 1,
          "presentation_rect": [
            184.0,
            6.0,
            102.0,
            142.0
          ],
          "bordercolor": [
            0.1725,
            0.2118,
            0.2667,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-12",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.0784,
            0.098,
            0.1294,
            1.0
          ],
          "border": 1,
          "rounded": 5.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            918.0,
            26.0,
            58.0,
            142.0
          ],
          "presentation": 1,
          "presentation_rect": [
            118.0,
            6.0,
            58.0,
            142.0
          ],
          "bordercolor": [
            0.1725,
            0.2118,
            0.2667,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-10",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.0784,
            0.098,
            0.1294,
            1.0
          ],
          "border": 1,
          "rounded": 5.0,
          "mode": 0,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            808.0,
            26.0,
            102.0,
            142.0
          ],
          "presentation": 1,
          "presentation_rect": [
            8.0,
            6.0,
            102.0,
            142.0
          ],
          "bordercolor": [
            0.1725,
            0.2118,
            0.2667,
            1.0
          ]
        }
      },
      {
        "box": {
          "id": "obj-9",
          "maxclass": "panel",
          "background": 1,
          "ignoreclick": 1,
          "bgcolor": [
            0.051,
            0.0627,
            0.0824,
            1.0
          ],
          "border": 1,
          "rounded": 8.0,
          "mode": 1,
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            800.0,
            20.0,
            562.0,
            169.0
          ],
          "presentation": 1,
          "presentation_rect": [
            0.0,
            0.0,
            562.0,
            169.0
          ],
          "bordercolor": [
            0.2039,
            0.2431,
            0.3059,
            1.0
          ],
          "grad1": [
            0.102,
            0.1216,
            0.1569,
            1.0
          ],
          "grad2": [
            0.051,
            0.0627,
            0.0824,
            1.0
          ],
          "proportion": 0.5,
          "bgfillcolor": {
            "angle": 270.0,
            "autogradient": 0,
            "color": [
              0.051,
              0.0627,
              0.0824,
              1.0
            ],
            "color1": [
              0.102,
              0.1216,
              0.1569,
              1.0
            ],
            "color2": [
              0.051,
              0.0627,
              0.0824,
              1.0
            ],
            "proportion": 0.5,
            "type": "gradient"
          }
        }
      }
    ],
    "lines": [
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-6",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-8",
            0
          ],
          "source": [
            "obj-7",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            1
          ],
          "source": [
            "obj-6",
            1
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-8",
            1
          ],
          "source": [
            "obj-7",
            1
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-29",
            0
          ],
          "source": [
            "obj-28",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-29",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-31",
            0
          ],
          "source": [
            "obj-30",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-31",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-33",
            0
          ],
          "source": [
            "obj-32",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-33",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-35",
            0
          ],
          "source": [
            "obj-34",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-35",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-37",
            0
          ],
          "source": [
            "obj-36",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-37",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-39",
            0
          ],
          "source": [
            "obj-38",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-39",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-41",
            0
          ],
          "source": [
            "obj-40",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-41",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-43",
            0
          ],
          "source": [
            "obj-42",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-43",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-45",
            0
          ],
          "source": [
            "obj-44",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-45",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-47",
            0
          ],
          "source": [
            "obj-46",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-47",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-49",
            0
          ],
          "source": [
            "obj-48",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-49",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-51",
            0
          ],
          "source": [
            "obj-50",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-51",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-53",
            0
          ],
          "source": [
            "obj-52",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-53",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-55",
            0
          ],
          "source": [
            "obj-54",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-55",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-58",
            0
          ],
          "source": [
            "obj-57",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-58",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-59",
            0
          ],
          "source": [
            "obj-57",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-60",
            0
          ],
          "source": [
            "obj-59",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-60",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-62",
            0
          ],
          "source": [
            "obj-61",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-62",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-63",
            0
          ],
          "source": [
            "obj-61",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-64",
            0
          ],
          "source": [
            "obj-63",
            0
          ]
        }
      },
      {
        "patchline": {
          "destination": [
            "obj-7",
            0
          ],
          "source": [
            "obj-64",
            0
          ]
        }
      }
    ]
  }
}
