#!/usr/bin/env python3
"""Generates the MMM Vocal Chopper devices (Max for Live, audio effects).

  python3 build_chopper.py  ->  MMM_VocalChopper.genexpr  (the engine, paste-able into any gen~ codebox)
                                MMM_VocalChopper.maxpat / .amxd   (the chopper: gen~ + live.* UI, 4 outs via send~)
                                MMM_ChopOut.maxpat / .amxd        (tiny receiver: put one per rack chain)

Why two devices: a Max for Live audio effect has exactly one stereo output. The chopper therefore renders FOUR voices
(= 4 stereo outs), plays voice 1 on its own output and ALSO publishes all four with send~ (mmmv1L ... mmmv4R). Drop the
chopper into chain 1 of an Audio Effect Rack and a "MMM Chop Out" into chains 2-4 (voice 2/3/4): every chain gets its own
effects after it.

GenExpr style follows what is proven to run in Live in ../../age12/m4l (Param / History / Data / peek / poke / floor /
min / max / pow / exp / log / cos / noise, plain if-blocks, every local initialised at the top, no loops, no ternary).
The grain pool is unrolled by this script instead of using Data arrays + for loops.
"""
import json, os, struct, sys

NG = 8            # grain pool size
BUF = 768000      # samples per channel (8 s @ 96 kHz)

# --------------------------------------------------------------------------- parameters
# (msg name, longname, short, min, max, init, unitstyle, type 0 float / 1 int, exponent)
# unitstyle: 0 int, 1 float, 2 ms, 3 Hz, 4 dB, 7 semitones
DIALS = {
    "simple": [
        ("rateHz",   "Rate Hz",    "Rate",   0.2,  30,   4,    3, 0, 2.0),   # free clock; goes to the ms metro, not to gen~
        ("p_chaos",  "Chaos",      "Chaos",  0,    1,    0.5,  1, 0, 1.0),
        ("p_size",   "Size",       "Size",   10,   2000, 150,  2, 0, 3.0),
        ("p_prob",   "Probability", "Prob",  0,    1,    1,    1, 0, 1.0),
        ("p_thr",    "Onset Threshold", "Thresh", -60, 0, -30, 4, 0, 1.0),
        ("p_dry",    "Dry",        "Dry",    0,    1,    0,    1, 0, 1.0),
    ],
    "mangle": [
        ("p_range",  "Range",      "Range",  0.02, 1,    0.6,  1, 0, 1.0),
        ("p_pitch",  "Pitch Scatter", "Pitch", 0,  24,   7,    7, 1, 1.0),
        ("p_rev",    "Reverse",    "Rev",    0,    1,    0.3,  1, 0, 1.0),
        ("p_rept",   "Repeats",    "Repeat", 1,    8,    1,    0, 1, 1.0),
        ("p_width",  "Width",      "Width",  0,    1,    0.6,  1, 0, 1.0),
        ("p_fade",   "Fade",       "Fade",   1,    100,  5,    2, 0, 2.0),
        ("p_lvlvar", "Level Variation", "LvlVar", 0, 1,  0.5,  1, 0, 1.0),
        ("p_bufsec", "Buffer Seconds", "Buffer", 0.5, 8, 4,    1, 0, 1.0),
        ("p_sens",   "Onset Sensitivity", "Sens", 1.2, 6, 2,   1, 0, 1.0),
        ("p_gap",    "Onset Gap",  "Gap",    10,   500,  60,   2, 0, 2.0),
    ],
    "lfo": [
        ("p_lfor",     "LFO Rate",  "LFO Rate", 0.05, 20,   2,   3, 0, 2.0),
        ("p_lfoslew",  "LFO Slew",  "Slew",     0,    2000, 50,  2, 0, 3.0),
        ("p_lfodepth", "LFO Depth", "Depth",    0,    1,    0.5, 1, 0, 1.0),
    ],
}
LFO_TARGETS = [("p_tsize", "Size", 1), ("p_tpitch", "Pitch", 1), ("p_trev", "Reverse", 1), ("p_tprob", "Prob", 0),
               ("p_trange", "Range", 0), ("p_twidth", "Width", 0), ("p_trept", "Repeat", 0), ("p_tchaos", "Chaos", 0)]
GEN_DEFAULTS = {d[0]: d[5] for pg in DIALS.values() for d in pg if d[0].startswith("p_")}
GEN_RANGES = {d[0]: (d[3], d[4]) for pg in DIALS.values() for d in pg if d[0].startswith("p_")}

# --------------------------------------------------------------------------- the GenExpr engine
def genexpr():
    P = []
    P += [("p_bufsec",), ]
    out = ["// MMM Vocal Chopper engine: rolling record buffer -> grain pool -> 4 stereo voices.",
           "// Generated by build_chopper.py - edit there, not here.",
           "// in1/in2 = live input; out1..out8 = voice1 L/R, voice2 L/R, voice3 L/R, voice4 L/R (dry is added to voice 1).",
           "// Counters p_tick / p_fire / p_panic: any change = one event (set by Max, no sample-accurate clock needed)."]
    for n, (lo, hi) in GEN_RANGES.items():
        out.append(f"Param {n}({GEN_DEFAULTS[n]}, min={lo}, max={hi});")
    out += [
        "Param p_hold(0, min=0, max=1);",
        "Param p_trigmode(0, min=0, max=2);      // 0 clock, 1 onset, 2 both",
        "Param p_outs(4, min=1, max=4);",
        "Param p_route(0, min=0, max=3);         // 0 random, 1 cycle, 2 by level, 3 by pitch",
        "Param p_tick(0, min=0, max=1000000000);",
        "Param p_fire(0, min=0, max=1000000000);",
        "Param p_panic(0, min=0, max=1000000000);",
        "Param p_lfo(0, min=0, max=1);",
        "Param p_lfotick(0, min=0, max=1);       // 1 = new S&H values on every chop step instead of the LFO clock",
    ]
    for n, _, d in LFO_TARGETS:
        out.append(f"Param {n}({d}, min=0, max=1);")
    out.append(f"Data bufL({BUF}); Data bufR({BUF});")
    out.append("History wr(0); History ef(0); History es(0); History gapc(0);")
    out.append("History prevtick(0); History prevfire(0); History prevpanic(0);")
    out.append("History repleft(0); History repcnt(0); History rr(0);")
    out.append("History lph(0);")
    out.append("History s_dur(1000); History s_start(0); History s_inc(1); History s_lg(1); History s_rg(1); History s_voice(0); History s_fade(100);")
    for i in range(1, 9):
        out.append(f"History sh{i}(0); History l{i}(0);")
    for g in range(NG):
        out.append(f"History g{g}act(0); History g{g}pos(0); History g{g}inc(1); History g{g}age(0); History g{g}len(1000); "
                   f"History g{g}fade(100); History g{g}lg(1); History g{g}rg(1); History g{g}v(0);")

    locals_ = ("inL inR m bl hd a ca cr cs thrl onset tk fi pn clkon lt lclk tau lf ev newg r sz dur semi inc dr span maxback bk far "
               "lv pn2 ang nv v u uu db pr slot best rm fd ee eo pw i0 i1 fr sa sb gl gr vv dry "
               "size_e pitch_e rev_e prob_e range_e width_e rept_e chaos_e o1 o2 o3 o4 o5 o6 o7 o8").split()
    out.append("")
    out.append("// ---- locals (all initialised) ----")
    out.append(" ".join(f"{n} = 0;" for n in locals_))
    out.append("""
inL = in1; inR = in2;
m = 0.5 * (inL + inR);
bl = floor(min(%d, max(1000, p_bufsec * samplerate)));
dry = max(0, min(1, p_dry));

// ---- record (hold = freeze the buffer) ----
hd = p_hold;
if (hd < 0.5) {
    poke(bufL, inL, wr);
    poke(bufR, inR, wr);
    wr = wr + 1;
    if (wr >= bl) { wr = 0; }
}
if (wr >= bl) { wr = 0; }

// ---- onset detector: fast envelope vs slow envelope, threshold + refractory gap ----
a = abs(m);
ca = 1 - exp(-1 / (0.001 * samplerate));
cr = 1 - exp(-1 / (0.03 * samplerate));
cs = 1 - exp(-1 / (0.25 * samplerate));
if (a > ef) { ef = ef + (a - ef) * ca; }
if (a <= ef) { ef = ef + (a - ef) * cr; }
es = es + (a - es) * cs;
thrl = pow(10, p_thr / 20);
if (gapc > 0) { gapc = gapc - 1; }
onset = 0;
if (p_trigmode > 0.5) {
    if (ef > thrl) {
        if (ef > es * p_sens) {
            if (gapc <= 0) { onset = 1; gapc = p_gap * 0.001 * samplerate; }
        }
    }
}

// ---- counters from Max ----
tk = 0; if (p_tick != prevtick) { tk = 1; } prevtick = p_tick;
fi = 0; if (p_fire != prevfire) { fi = 1; } prevfire = p_fire;
pn = 0; if (p_panic != prevpanic) { pn = 1; } prevpanic = p_panic;
clkon = 1;
if (p_trigmode > 0.5) { if (p_trigmode < 1.5) { clkon = 0; } }

// ---- sample & hold LFO: 8 independent values, smoothed by Slew ----
lph = lph + max(0.05, p_lfor) / samplerate;
lt = 0;
if (lph >= 1) { lph = lph - 1; lt = 1; }
lclk = lt;
if (p_lfotick > 0.5) { lclk = tk; }
if (lclk > 0.5) {
    sh1 = noise(); sh2 = noise(); sh3 = noise(); sh4 = noise(); sh5 = noise(); sh6 = noise(); sh7 = noise(); sh8 = noise();
}
tau = max(1, p_lfoslew * 0.001 * samplerate);
l1 = l1 + (sh1 - l1) / tau; l2 = l2 + (sh2 - l2) / tau; l3 = l3 + (sh3 - l3) / tau; l4 = l4 + (sh4 - l4) / tau;
l5 = l5 + (sh5 - l5) / tau; l6 = l6 + (sh6 - l6) / tau; l7 = l7 + (sh7 - l7) / tau; l8 = l8 + (sh8 - l8) / tau;
lf = 0;
if (p_lfo > 0.5) { lf = max(0, min(1, p_lfodepth)); }

// ---- event: clock tick, onset or Fire button ----
ev = fi;
if (onset > 0.5) { ev = 1; }
if (tk > 0.5) { if (clkon > 0.5) { ev = 1; } }
newg = 0;
if (ev > 0.5) {
    size_e = p_size * pow(2, lf * p_tsize * l1 * 2);
    pitch_e = min(24, max(0, p_pitch + lf * p_tpitch * l2 * 12));
    rev_e = min(1, max(0, p_rev + lf * p_trev * l3 * 0.5));
    prob_e = min(1, max(0, p_prob + lf * p_tprob * l4 * 0.5));
    range_e = min(1, max(0.02, p_range + lf * p_trange * l5 * 0.5));
    width_e = min(1, max(0, p_width + lf * p_twidth * l6 * 0.5));
    rept_e = min(8, max(1, p_rept + lf * p_trept * l7 * 3));
    chaos_e = min(1, max(0, p_chaos + lf * p_tchaos * l8 * 0.5));
    r = (noise() + 1) * 0.5;
    if (fi > 0.5) { r = 0; }
    if (r <= prob_e) {
        // length: Size, spread by Chaos (up to +-1.5 octaves)
        sz = size_e * pow(2, noise() * chaos_e * 1.5);
        sz = max(10, min(3000, sz));
        dur = sz * 0.001 * samplerate;
        // pitch scatter in whole semitones, reverse
        semi = floor(noise() * pitch_e * chaos_e + 0.5);
        inc = pow(2, semi / 12);
        dr = 1;
        u = (noise() + 1) * 0.5;
        if (u < rev_e * chaos_e) { dr = -1; }
        dur = min(dur, (bl - 2000) / inc);
        span = dur * inc;
        // position: somewhere inside the last Range * buffer, never past the write head
        maxback = max(0, range_e * bl - span);
        bk = (noise() + 1) * 0.5 * maxback;
        far = bk + span;
        s_start = wr - far;
        if (dr < 0) { s_start = wr - bk; }
        s_inc = inc * dr;
        s_dur = dur;
        s_fade = max(8, min(dur * 0.5, p_fade * 0.001 * samplerate));
        // level + pan (equal power)
        lv = 1 - (noise() + 1) * 0.5 * p_lvlvar * chaos_e;
        pn2 = noise() * width_e;
        ang = (pn2 * 0.5 + 0.5) * 1.5707963;
        s_lg = cos(ang) * 1.41421 * lv;
        s_rg = sin(ang) * 1.41421 * lv;
        // which of the 4 outs
        nv = max(1, min(4, floor(p_outs + 0.5)));
        v = 0;
        u = (noise() + 1) * 0.5;
        if (p_route < 0.5) { v = floor(u * nv); }
        if (p_route >= 0.5) { if (p_route < 1.5) { rr = rr + 1; if (rr >= nv) { rr = 0; } v = rr; } }
        if (p_route >= 1.5) {
            if (p_route < 2.5) {
                db = 20 * log(ef + 0.000001) / 2.302585;
                uu = max(0, min(0.999, (db + 50) / 45));
                v = floor(uu * nv);
            }
        }
        if (p_route >= 2.5) {
            pr = max(1, pitch_e * chaos_e);
            uu = max(0, min(0.999, (semi / pr) * 0.5 + 0.5));
            v = floor(uu * nv);
        }
        s_voice = min(v, nv - 1);
        repleft = floor(rept_e + 0.5) - 1;
        repcnt = dur;
        newg = 1;
    }
}
// repeats (stutter): same slice again, back to back
if (newg < 0.5) {
    if (repleft > 0.5) {
        repcnt = repcnt - 1;
        if (repcnt <= 0) { newg = 1; repleft = repleft - 1; repcnt = s_dur; }
    }
}

// ---- panic: stop everything ----
if (pn > 0.5) {
    repleft = 0; newg = 0;
%s}

// ---- allocate a grain: lowest free slot, else steal the one closest to its end ----
if (newg > 0.5) {
    slot = -1;
%s    if (slot < 0) {
        best = 1000000000;
%s    }
%s}
""" % (BUF,
       "".join(f"    g{g}act = 0;\n" for g in range(NG)),
       "".join(f"    if (g{g}act < 0.5) {{ slot = {g}; }}\n" for g in reversed(range(NG))),
       "".join(f"        rm = g{g}len - g{g}age; if (rm < best) {{ best = rm; slot = {g}; }}\n" for g in range(NG)),
       "".join(f"    if (slot == {g}) {{ g{g}pos = s_start; g{g}inc = s_inc; g{g}age = 0; g{g}len = s_dur; g{g}fade = s_fade; "
               f"g{g}lg = s_lg; g{g}rg = s_rg; g{g}v = s_voice; g{g}act = 1; }}\n" for g in range(NG))))

    out.append("// ---- grains: linear interpolation, smoothstep fade in/out ----")
    for g in range(NG):
        out.append(f"""if (g{g}act > 0.5) {{
    fd = g{g}fade;
    ee = g{g}age / fd; if (ee > 1) {{ ee = 1; }}
    eo = (g{g}len - g{g}age) / fd; if (eo > 1) {{ eo = 1; }}
    if (eo < ee) {{ ee = eo; }}
    if (ee < 0) {{ ee = 0; }}
    ee = ee * ee * (3 - 2 * ee);
    pw = g{g}pos; pw = pw - bl * floor(pw / bl);
    i0 = floor(pw); fr = pw - i0; i1 = i0 + 1; if (i1 >= bl) {{ i1 = 0; }}
    sa = peek(bufL, i0); sa = sa + (peek(bufL, i1) - sa) * fr;
    sb = peek(bufR, i0); sb = sb + (peek(bufR, i1) - sb) * fr;
    gl = sa * ee * g{g}lg; gr = sb * ee * g{g}rg;
    vv = g{g}v;
    if (vv < 0.5) {{ o1 = o1 + gl; o2 = o2 + gr; }}
    if (vv > 0.5) {{ if (vv < 1.5) {{ o3 = o3 + gl; o4 = o4 + gr; }} }}
    if (vv > 1.5) {{ if (vv < 2.5) {{ o5 = o5 + gl; o6 = o6 + gr; }} }}
    if (vv > 2.5) {{ o7 = o7 + gl; o8 = o8 + gr; }}
    g{g}pos = g{g}pos + g{g}inc;
    g{g}age = g{g}age + 1;
    if (g{g}age >= g{g}len) {{ g{g}act = 0; }}
}}""")
    out.append("""
out1 = o1 + inL * dry; out2 = o2 + inR * dry;
out3 = o3; out4 = o4; out5 = o5; out6 = o6; out7 = o7; out8 = o8;
""")
    return "\n".join(out)

# --------------------------------------------------------------------------- patcher helpers
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "age12", "m4l"))
from build_device import finish, amxd_bytes   # same patcher header + .amxd container as the AGE12 device (runs in Live)

class Patch:
    def __init__(self):
        self.boxes, self.lines, self.n, self.vars = [], [], 0, {}
        self.cx, self.cy = 30, 400   # patching-view cursor (layout only, no meaning)

    def _id(self):
        self.n += 1
        return f"obj-{self.n}"

    def add(self, **kw):
        i = self._id()
        if "patching_rect" not in kw:
            kw["patching_rect"] = [float(self.cx), float(self.cy), 120.0, 22.0]
            self.cy += 28
            if self.cy > 1100:
                self.cy, self.cx = 400, self.cx + 170
        self.boxes.append({"box": dict(id=i, **kw)})
        return i

    def obj(self, text, nin, nout, outtypes=None, **kw):
        return self.add(maxclass="newobj", text=text, numinlets=nin, numoutlets=nout, outlettype=outtypes or [""] * nout, **kw)

    def msg(self, text, **kw):
        return self.add(maxclass="message", text=text, numinlets=2, numoutlets=1, outlettype=[""], **kw)

    def line(self, a, ao, b, bi):
        self.lines.append({"patchline": {"destination": [b, bi], "source": [a, ao]}})

    # ---- live.* controls (presentation)
    def _pres(self, kw, rect, page=None, hidden=False):
        kw.update(presentation=1, presentation_rect=[float(v) for v in rect])
        if hidden:
            kw["hidden"] = 1

    def dial(self, d, rect, page=None, hidden=False):
        name, longn, short, mn, mx, init, unit, typ, exp = d
        kw = dict(maxclass="live.dial", numinlets=1, numoutlets=2, outlettype=["", "float"], parameter_enable=1,
                  varname=longn.replace(" ", "_"), fontsize=9.0,
                  saved_attribute_attributes={"valueof": {"parameter_initial": [init], "parameter_initial_enable": 1,
                      "parameter_longname": longn, "parameter_mmax": float(mx), "parameter_mmin": float(mn),
                      "parameter_shortname": short, "parameter_type": typ, "parameter_unitstyle": unit,
                      "parameter_exponent": exp}})
        self._pres(kw, rect, page, hidden)
        i = self.add(**kw)
        self.vars[i] = (kw["varname"], page)
        return i

    def enum(self, cls, longn, short, items, init, rect, page=None, hidden=False, **extra):
        kw = dict(maxclass=cls, numinlets=1, numoutlets=3, outlettype=["", "", "float"], parameter_enable=1,
                  varname=longn.replace(" ", "_"), fontsize=9.0,
                  saved_attribute_attributes={"valueof": {"parameter_enum": items, "parameter_initial": [init],
                      "parameter_initial_enable": 1, "parameter_longname": longn, "parameter_mmax": len(items) - 1,
                      "parameter_shortname": short, "parameter_type": 2}})
        kw.update(extra)
        self._pres(kw, rect, page, hidden)
        i = self.add(**kw)
        self.vars[i] = (kw["varname"], page)
        return i

    def text(self, longn, label, init, rect, mode=1, page=None, hidden=False):
        kw = dict(maxclass="live.text", numinlets=1, numoutlets=2, outlettype=["", ""], parameter_enable=1, mode=mode,
                  text=label, texton=label, varname=longn.replace(" ", "_"), fontsize=9.0,
                  saved_attribute_attributes={"valueof": {"parameter_enum": ["off", "on"], "parameter_initial": [init],
                      "parameter_initial_enable": 1, "parameter_longname": longn, "parameter_mmax": 1,
                      "parameter_shortname": label, "parameter_type": 2}})
        self._pres(kw, rect, page, hidden)
        i = self.add(**kw)
        self.vars[i] = (kw["varname"], page)
        return i

    def comment(self, label, rect, page=None, hidden=False, size=9.0, bold=0):
        vn = "lbl_" + label.replace(" ", "_").replace("/", "_").lower() + f"_{self.n + 1}"
        kw = dict(maxclass="comment", text=label, numinlets=1, numoutlets=0, varname=vn, fontsize=size, fontface=bold)
        self._pres(kw, rect, page, hidden)
        i = self.add(**kw)
        self.vars[i] = (vn, page)
        return i

# --------------------------------------------------------------------------- chopper device
DIVS = [("1/1", "1n"), ("1/2", "2n"), ("1/4", "4n"), ("1/8", "8n"), ("1/16", "16n"), ("1/32", "32n"), ("1/8T", "8nt"), ("1/16T", "16nt")]

def build_chopper(code):
    p = Patch()
    # ---- gen~ (embedded patcher with one codebox)
    gin = [dict(id=f"obj-{i}", maxclass="newobj", text=f"in {i}", numinlets=0, numoutlets=1, outlettype=[""],
                patching_rect=[30.0 + 80 * (i - 1), 30.0, 40.0, 22.0]) for i in (1, 2)]
    gcode = dict(id="obj-3", maxclass="codebox", code=code, numinlets=2, numoutlets=8, outlettype=[""] * 8,
                 patching_rect=[30.0, 80.0, 760.0, 600.0], fontname="Menlo", fontsize=11.0)
    gout = [dict(id=f"obj-{3 + i}", maxclass="newobj", text=f"out {i}", numinlets=1, numoutlets=0,
                 patching_rect=[30.0 + 80 * (i - 1), 720.0, 40.0, 22.0]) for i in range(1, 9)]
    gboxes = [{"box": b} for b in gin + [gcode] + gout]
    glines = []
    for i in range(2):
        glines.append({"patchline": {"destination": ["obj-3", i], "source": [f"obj-{i + 1}", 0]}})
    for i in range(8):
        glines.append({"patchline": {"destination": [f"obj-{4 + i}", 0], "source": ["obj-3", i]}})
    gen_patcher = {"fileversion": 1, "appversion": {"major": 8, "minor": 6, "revision": 2, "architecture": "x64", "modernui": 1},
                   "classnamespace": "dsp.gen", "rect": [100.0, 100.0, 840.0, 780.0], "bglocked": 0, "openinpresentation": 0,
                   "default_fontsize": 12.0, "default_fontface": 0, "default_fontname": "Arial", "gridonopen": 1,
                   "gridsize": [15.0, 15.0], "gridsnaponopen": 1, "objectsnaponopen": 1, "statusbarvisible": 2,
                   "toolbarvisible": 1, "lefttoolbarpinned": 0, "toptoolbarpinned": 0, "righttoolbarpinned": 0,
                   "bottomtoolbarpinned": 0, "toolbars_unpinned_last_save": 0, "tallnewobj": 0, "boxanimatetime": 200,
                   "enablehscroll": 1, "enablevscroll": 1, "devicewidth": 0.0, "description": "", "digest": "", "tags": "",
                   "style": "", "subpatcher_template": "", "assistshowspatchername": 0, "boxes": gboxes, "lines": glines}

    plugin = p.obj("plugin~", 2, 2, ["signal", "signal"])
    gen = p.add(maxclass="newobj", text="gen~", numinlets=2, numoutlets=8, outlettype=["signal"] * 8, patcher=gen_patcher)
    plugout = p.obj("plugout~", 2, 0)
    for i in range(2):
        p.line(plugin, i, gen, i)
        p.line(gen, i, plugout, i)
    names = ["mmmv1L", "mmmv1R", "mmmv2L", "mmmv2R", "mmmv3L", "mmmv3R", "mmmv4L", "mmmv4R"]
    for i, nm in enumerate(names):
        s = p.obj(f"send~ {nm}", 1, 0)
        p.line(gen, i, s, 0)

    def to_gen(src, srcout, name, extra=None):
        pp = p.obj(f"prepend {name}", 1, 1)
        p.line(src, srcout, pp, 0)
        if extra:
            pass
        p.line(pp, 0, gen, 0)
        return pp

    # ---- header strip (always visible)
    page = p.enum("live.tab", "Page", "Page", ["Simple", "Mangle", "LFO"], 0, [6, 6, 150, 18])
    trig = p.enum("live.menu", "Trigger", "Trigger", ["Clock", "Onset", "Both"], 0, [166, 6, 62, 18])
    hold = p.text("Hold", "Hold", 0, [234, 6, 44, 18])
    fire = p.text("Fire", "Fire", 0, [284, 6, 44, 18], mode=0)
    panic = p.text("Panic", "Panic", 0, [334, 6, 44, 18], mode=0)
    sync = p.text("Sync", "Sync", 0, [384, 6, 44, 18])
    p.comment("MMM VOCAL CHOP", [446, 8, 140, 14], size=10.0, bold=1)
    to_gen(trig, 0, "p_trigmode")
    to_gen(hold, 0, "p_hold")

    # fire / panic: button may emit bang or 1/0 -> [route bang 1] handles both, then a counter makes "any change" an event
    for src, nm in ((fire, "p_fire"), (panic, "p_panic")):
        rt = p.obj("route bang 1", 1, 3)
        ct = p.obj("counter", 3, 4, ["int", "int", "int", "int"])
        p.line(src, 0, rt, 0)
        p.line(rt, 0, ct, 0)
        p.line(rt, 1, ct, 0)
        to_gen(ct, 0, nm)

    # ---- clock: tempo-synced metro (Sync on) or free metro in ms (Sync off); both feed one counter -> p_tick
    metro_a = p.obj("metro 16n @quantize 16n @active 0", 2, 1)
    metro_b = p.obj("metro 250 @active 1", 2, 1)
    tick_ct = p.obj("counter", 3, 4, ["int", "int", "int", "int"])
    p.line(metro_a, 0, tick_ct, 0)
    p.line(metro_b, 0, tick_ct, 0)
    to_gen(tick_ct, 0, "p_tick")
    p.line(sync, 0, metro_a, 0)
    inv = p.obj("== 0", 2, 1)
    p.line(sync, 0, inv, 0)
    p.line(inv, 0, metro_b, 0)

    # division menu -> metro A
    div = p.enum("live.menu", "Division", "Div", [d[0] for d in DIVS], 4, [62, 48, 50, 18], page="simple")
    sel = p.obj("select " + " ".join(str(i) for i in range(len(DIVS))), 1, len(DIVS) + 1)
    p.line(div, 0, sel, 0)
    for i, (_, nv) in enumerate(DIVS):
        m = p.msg(f"interval {nv}, quantize {nv}")
        p.line(sel, i, m, 0)
        p.line(m, 0, metro_a, 0)

    # ---- dials
    pos = {}
    simple_x = {"rateHz": 8, "p_chaos": 118, "p_size": 172, "p_prob": 226, "p_thr": 280, "p_dry": 334}
    for d in DIALS["simple"]:
        i = p.dial(d, [simple_x[d[0]], 32, 46, 48], page="simple")
        pos[d[0]] = i
        if d[0] == "rateHz":
            bang = p.obj("!/ 1000.", 2, 1)
            p.line(i, 0, bang, 0)
            p.line(bang, 0, metro_b, 1)     # ms interval into the right inlet
        else:
            to_gen(i, 0, d[0])
    p.comment("DIV (Sync)", [62, 34, 60, 12], page="simple")
    p.comment("Rate = free Hz", [8, 82, 90, 12], page="simple", size=8.0)
    p.comment("Chaos scales all random amounts", [118, 82, 200, 12], page="simple", size=8.0)

    outs = p.enum("live.menu", "Outs", "Outs", ["1 out", "2 outs", "3 outs", "4 outs"], 3, [396, 48, 90, 18], page="simple")
    plus = p.obj("+ 1", 2, 1)
    p.line(outs, 0, plus, 0)
    to_gen(plus, 0, "p_outs")
    route = p.enum("live.menu", "Route", "Route", ["Random", "Cycle", "By level", "By pitch"], 0, [396, 100, 90, 18], page="simple")
    to_gen(route, 0, "p_route")
    p.comment("OUTS", [396, 34, 60, 12], page="simple")
    p.comment("ROUTE slices to outs", [396, 86, 130, 12], page="simple")

    for k, d in enumerate(DIALS["mangle"]):
        i = p.dial(d, [8 + 57 * k, 36, 46, 48], page="mangle", hidden=True)
        to_gen(i, 0, d[0])
    p.comment("max amounts at Chaos 100 %", [8, 90, 200, 12], page="mangle", hidden=True, size=8.0)

    lfo_on = p.text("LFO On", "LFO ON", 0, [8, 36, 56, 24], page="lfo", hidden=True)
    to_gen(lfo_on, 0, "p_lfo")
    tick_on = p.text("LFO Per Step", "Per step", 0, [8, 66, 56, 24], page="lfo", hidden=True)
    to_gen(tick_on, 0, "p_lfotick")
    for k, d in enumerate(DIALS["lfo"]):
        i = p.dial(d, [76 + 57 * k, 32, 46, 48], page="lfo", hidden=True)
        to_gen(i, 0, d[0])
    p.comment("S&H LFO animates the ticked targets:", [8, 98, 240, 12], page="lfo", hidden=True)
    for k, (nm, lab, init) in enumerate(LFO_TARGETS):
        t = p.text("LFO > " + lab, lab, init, [8 + 62 * k, 114, 58, 22], page="lfo", hidden=True)
        to_gen(t, 0, nm)

    # ---- page switching: show/hide with thispatcher (hidden objects keep working)
    tp = p.obj("thispatcher", 1, 2)
    dl = p.obj("deferlow", 1, 1)
    p.line(dl, 0, tp, 0)
    sel_p = p.obj("select 0 1 2", 1, 4)
    p.line(page, 0, sel_p, 0)
    pages = ["simple", "mangle", "lfo"]
    members = [(vn, pg) for (vn, pg) in p.vars.values() if pg]
    for k, pgname in enumerate(pages):
        cmds = ", ".join(f"script sendbox {vn} hidden {0 if pg == pgname else 1}" for vn, pg in members)
        m = p.msg(cmds)
        p.line(sel_p, k, m, 0)
        p.line(m, 0, dl, 0)
    return finish(p.boxes, p.lines, 600.0, "MMM Vocal Chopper: chaotic live vocal chopper with 4 voice outs (rack workflow)")

# --------------------------------------------------------------------------- receiver device
def build_chopout():
    p = Patch()
    plugin = p.obj("plugin~", 2, 2, ["signal", "signal"])
    plugout = p.obj("plugout~", 2, 0)
    tab = p.enum("live.tab", "Voice", "Voice", ["1", "2", "3", "4"], 1, [6, 6, 120, 20])
    dry = p.dial(("dry", "Dry", "Dry", 0, 1, 0, 1, 0, 1.0), [134, 4, 46, 48])
    lvl = p.dial(("lvl", "Level", "Level", 0, 1.5, 1, 1, 0, 1.0), [186, 4, 46, 48])
    p.comment("MMM CHOP OUT", [6, 32, 120, 14], size=10.0, bold=1)
    p.comment("voice from the chopper", [6, 48, 126, 12], size=8.0)
    plus = p.obj("+ 1", 2, 1)
    p.line(tab, 0, plus, 0)
    dl, ll = [], []
    for side, pin in (("L", 0), ("R", 1)):
        sp = p.obj(f"sprintf set mmmv%d{side}", 1, 1)
        p.line(plus, 0, sp, 0)
        rc = p.obj(f"receive~ mmmv2{side}", 1, 1, ["signal"])
        p.line(sp, 0, rc, 0)
        gl = p.obj("*~ 1.", 2, 1, ["signal"])      # level
        gd = p.obj("*~ 0.", 2, 1, ["signal"])      # dry
        su = p.obj("+~", 2, 1, ["signal"])
        p.line(rc, 0, gl, 0)
        p.line(plugin, pin, gd, 0)
        p.line(gl, 0, su, 0)
        p.line(gd, 0, su, 1)
        p.line(su, 0, plugout, pin)
        dl.append(gd)
        ll.append(gl)
    for dial_, gains, nm in ((dry, dl, "dry"), (lvl, ll, "lvl")):
        pk = p.obj("pak 0. 20", 2, 1)
        ln = p.obj("line~", 2, 1, ["signal"])
        p.line(dial_, 0, pk, 0)
        p.line(pk, 0, ln, 0)
        for g in gains:
            p.line(ln, 0, g, 1)
    return finish(p.boxes, p.lines, 240.0, "MMM Chop Out: receives one voice of the MMM Vocal Chopper (put one per rack chain)")


def write(doc, base):
    with open(base + ".maxpat", "w") as f:
        f.write(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")
    with open(base + ".amxd", "wb") as f:
        f.write(amxd_bytes(doc))

if __name__ == "__main__":
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    code = genexpr()
    open("MMM_VocalChopper.genexpr", "w").write(code + "\n")
    write(build_chopper(code), "MMM_VocalChopper")
    write(build_chopout(), "MMM_ChopOut")
    for fn in ("MMM_VocalChopper.maxpat", "MMM_ChopOut.maxpat"):
        json.loads(open(fn).read())
    print("wrote MMM_VocalChopper.{genexpr,maxpat,amxd}, MMM_ChopOut.{maxpat,amxd}")
